import Foundation

enum NameGenerator {

    static let pokemonNames = [
        "bulbasaur", "charmander", "squirtle", "butterfree", "beedrill",
        "pidgeot", "pikachu", "sandslash", "nidoqueen", "nidoking",
        "clefable", "ninetales", "wigglytuff", "golbat", "vileplume",
        "parasect", "venomoth", "dugtrio", "persian", "golduck",
        "primeape", "arcanine", "poliwrath", "alakazam", "machamp",
        "victreebel", "tentacruel", "golem", "rapidash", "slowbro",
        "magneton", "dodrio", "dewgong", "muk", "cloyster", "gengar",
        "hypno", "kingler", "electrode", "exeggutor", "marowak",
        "hitmonlee", "hitmonchan", "lickitung", "rhydon", "chansey",
        "tangela", "kangaskhan", "horsea", "seadra", "staryu",
        "mrmime", "scyther", "jynx", "electabuzz", "magmar",
        "pinsir", "tauros", "lapras", "ditto", "eevee",
        "vaporeon", "jolteon", "flareon", "porygon", "omanyte",
        "omastar", "kabuto", "kabutops", "aerodactyl", "snorlax",
        "articuno", "zapdos", "moltres", "dratini", "dragonair",
        "dragonite", "mewtwo", "mew", "chikorita", "cyndaquil",
        "totodile", "meganium", "typhlosion", "feraligatr",
    ]

    // Legacy word lists kept only for isAutoGenerated() backward compatibility.
    private static let legacyAdjectives = [
        "swift", "bright", "calm", "dark", "eager", "fair", "glad", "hazy",
        "keen", "lush", "mild", "neat", "odd", "pale", "quick", "rare",
        "sharp", "tall", "vast", "warm", "bold", "crisp", "deep", "fine",
        "gold", "high", "iron", "jade", "kind", "lean", "moss", "nova",
        "amber", "ashen", "azure", "clear", "dense", "fleet", "fresh", "grand",
        "green", "grey", "hardy", "light", "lone", "lucid", "noble", "plush",
        "prime", "pure", "quiet", "rough", "rust", "sage", "sleek", "slim",
        "soft", "stout", "terse", "true", "twin", "vivid", "wild", "wry",
    ]

    private static let legacyNouns = [
        "falcon", "brook", "cedar", "delta", "ember", "frost", "grove", "haven",
        "inlet", "jewel", "knoll", "larch", "maple", "nexus", "orbit", "pearl",
        "quill", "ridge", "shore", "thorn", "umbra", "vault", "whale", "xenon",
        "birch", "coral", "dusk", "fern", "gale", "heron", "ivory", "junco",
        "alder", "aspen", "bloom", "briar", "cliff", "crane", "creek", "crest",
        "drift", "finch", "flame", "flint", "forge", "glen", "heath", "ledge",
        "lotus", "lumen", "marsh", "opal", "pine", "plume", "raven", "reef",
        "robin", "slate", "spark", "spire", "stone", "trail", "vale", "wren",
    ]

    /// Returns the Pokemon name at `counter % pokemonNames.count`.
    static func generate(counter: Int) -> String {
        let index = counter % pokemonNames.count
        return pokemonNames[index]
    }

    /// Returns `true` when `name` matches an auto-generated pattern:
    /// - A Pokemon name (e.g. "pikachu")
    /// - A Pokemon name with numeric suffix (e.g. "pikachu-2")
    /// - Legacy "adjective-noun" or "adjective-noun-N" format
    static func isAutoGenerated(_ name: String) -> Bool {
        let parts = name.split(separator: "-").map(String.init)

        // Single-part: bare Pokemon name
        if parts.count == 1 {
            return pokemonNames.contains(parts[0])
        }

        // Two parts: could be "pokemon-N" (new) or "adjective-noun" (legacy)
        if parts.count == 2 {
            if pokemonNames.contains(parts[0]), Int(parts[1]) != nil {
                return true
            }
            if legacyAdjectives.contains(parts[0]), legacyNouns.contains(parts[1]) {
                return true
            }
            return false
        }

        // Three parts: legacy "adjective-noun-N"
        if parts.count == 3 {
            if legacyAdjectives.contains(parts[0]), legacyNouns.contains(parts[1]), Int(parts[2]) != nil {
                return true
            }
            return false
        }

        return false
    }
}
