import AppKit
import Foundation
import Testing
import MagentCore

// MARK: - KeyBinding

@Suite("KeyBinding defaults")
struct KeyBindingDefaultsTests {

    @Test("Recenter current thread defaults to Cmd+J")
    func recenterCurrentThreadDefaultsToCommandJ() {
        let binding = KeyBindingSettings().binding(for: .recenterCurrentThread)

        #expect(binding.keyCode == 38)
        #expect(binding.modifiers == [.command])
        #expect(binding.menuKeyEquivalent == "j")
        #expect(binding.displayString == "\u{2318}J")
    }
}

@Suite("MagentThread activity duration state")
struct MagentThreadActivityDurationStateTests {

    @Test("Describes an idle duration as last activity")
    func idleDurationIsLastActivity() {
        var thread = MagentThread(
            projectId: UUID(),
            name: "thread",
            worktreePath: "/tmp/thread",
            branchName: "thread"
        )
        thread.busyStateSince = Date().addingTimeInterval(-11 * 86_400)

        #expect(thread.activityDurationState == .lastActivity)
    }

    @Test("Describes a working duration as busy")
    func busyDurationIsBusy() {
        var thread = MagentThread(
            projectId: UUID(),
            name: "thread",
            worktreePath: "/tmp/thread",
            branchName: "thread"
        )
        thread.busyStateSince = Date().addingTimeInterval(-60)
        thread.busySessions.insert("session")

        #expect(thread.activityDurationState == .busy)
    }
}

@Suite("Thread activity indicator preference")
struct ThreadActivityIndicatorPreferenceTests {

    @Test("Migrates saved settings without an explicit preference to the circle")
    func missingPreferenceDefaultsToCircle() throws {
        let settings = try JSONDecoder().decode(AppSettings.self, from: Data(#"{"projects":[]}"#.utf8))

        #expect(settings.threadActivityIndicatorStyle == .circle)
    }

    @Test("Preserves an explicit text preference")
    func explicitTextPreferenceRoundTrips() throws {
        var settings = AppSettings()
        settings.threadActivityIndicatorStyle = .text

        let decoded = try JSONDecoder().decode(AppSettings.self, from: JSONEncoder().encode(settings))

        #expect(decoded.threadActivityIndicatorStyle == .text)
    }
}

// MARK: - SemanticVersion

@Suite("SemanticVersion parsing")
struct SemanticVersionTests {

    @Test("Parses full x.y.z version")
    func parsesFullVersion() throws {
        let v = try #require(SemanticVersion("1.2.3"))
        #expect(v.major == 1 && v.minor == 2 && v.patch == 3)
    }

    @Test("Accepts leading v/V prefix")
    func parsesLeadingV() throws {
        #expect(SemanticVersion("v1.2.3")?.displayString == "1.2.3")
        #expect(SemanticVersion("V2.0.0")?.displayString == "2.0.0")
    }

    @Test("Defaults missing components to 0")
    func parsesShortForm() throws {
        let major = try #require(SemanticVersion("4"))
        #expect(major.major == 4 && major.minor == 0 && major.patch == 0)

        let majMinor = try #require(SemanticVersion("4.5"))
        #expect(majMinor.minor == 5 && majMinor.patch == 0)
    }

    @Test("Strips pre-release / build suffix after first dash")
    func stripsSuffix() throws {
        let v = try #require(SemanticVersion("1.2.3-alpha.4"))
        #expect(v.major == 1 && v.minor == 2 && v.patch == 3)
    }

    @Test("Trims surrounding whitespace")
    func trimsWhitespace() throws {
        #expect(SemanticVersion("  1.0.0 \n")?.displayString == "1.0.0")
    }

    @Test("Rejects non-numeric components")
    func rejectsNonNumeric() {
        #expect(SemanticVersion("abc") == nil)
        #expect(SemanticVersion("1.x.0") == nil)
        #expect(SemanticVersion("") == nil)
    }

    @Test("Comparable orders major/minor/patch correctly")
    func comparable() throws {
        let a = try #require(SemanticVersion("1.2.3"))
        let b = try #require(SemanticVersion("1.2.4"))
        let c = try #require(SemanticVersion("1.3.0"))
        let d = try #require(SemanticVersion("2.0.0"))
        #expect(a < b)
        #expect(b < c)
        #expect(c < d)
        #expect(!(d < a))
    }
}

// MARK: - NameGenerator

@Suite("NameGenerator.isAutoGenerated")
struct NameGeneratorTests {

    @Test("Recognizes bare pokemon names")
    func bareName() {
        #expect(NameGenerator.isAutoGenerated("pikachu"))
        #expect(NameGenerator.isAutoGenerated("whiscash"))
    }

    @Test("Recognizes pokemon with numeric suffix")
    func numericSuffix() {
        #expect(NameGenerator.isAutoGenerated("pikachu-2"))
        #expect(NameGenerator.isAutoGenerated("eevee-42"))
    }

    @Test("Rejects pokemon with non-numeric suffix")
    func pokemonNonNumeric() {
        #expect(!NameGenerator.isAutoGenerated("pikachu-foo"))
    }

    @Test("Recognizes legacy adjective-noun form")
    func legacyTwoPart() {
        #expect(NameGenerator.isAutoGenerated("swift-falcon"))
        #expect(NameGenerator.isAutoGenerated("bright-brook"))
    }

    @Test("Recognizes legacy adjective-noun-N form")
    func legacyThreePart() {
        #expect(NameGenerator.isAutoGenerated("swift-falcon-7"))
    }

    @Test("Rejects three-part with non-numeric tail")
    func legacyThreePartBad() {
        #expect(!NameGenerator.isAutoGenerated("swift-falcon-foo"))
    }

    @Test("Rejects arbitrary/custom names")
    func customNames() {
        #expect(!NameGenerator.isAutoGenerated("my-feature-branch"))
        #expect(!NameGenerator.isAutoGenerated("fix-bug-in-login"))
        #expect(!NameGenerator.isAutoGenerated("unknownword"))
    }

    @Test("Generate wraps counter modulo pokemonNames count")
    func generateWraps() {
        let count = NameGenerator.pokemonNames.count
        #expect(NameGenerator.generate(counter: 0) == NameGenerator.pokemonNames[0])
        #expect(NameGenerator.generate(counter: count) == NameGenerator.pokemonNames[0])
        #expect(NameGenerator.generate(counter: count + 3) == NameGenerator.pokemonNames[3])
    }
}

// MARK: - shellQuote

@Suite("shellQuote")
struct ShellQuoteTests {

    @Test("Wraps plain strings in single quotes")
    func plain() {
        #expect(shellQuote("hello") == "'hello'")
    }

    @Test("Preserves spaces and special chars")
    func spacesAndSpecials() {
        #expect(shellQuote("a b c") == "'a b c'")
        #expect(shellQuote("$HOME `whoami`") == "'$HOME `whoami`'")
    }

    @Test("Escapes embedded single quotes via close-escape-reopen idiom")
    func embeddedQuote() {
        // "don't" → 'don'\''t'
        #expect(shellQuote("don't") == #"'don'\''t'"#)
    }

    @Test("Handles empty string")
    func empty() {
        #expect(shellQuote("") == "''")
    }
}

// MARK: - Codex app-server recovery

@Suite("Codex app-server stale-thread recovery heuristic")
struct CodexAppServerRecoveryTests {

    @Test("Requests fresh thread retry for stale resume failures")
    func retriesForStaleResumeFailure() {
        let shouldRetry = AgentChatRuntime.shouldRetryCodexWithFreshThread(
            previousConversationSessionID: "thread_123",
            appServerText: "Codex app-server failed: thread not found"
        )
        #expect(shouldRetry)
    }

    @Test("Requests fresh thread retry for closed/expired thread errors")
    func retriesForClosedThreadFailure() {
        let shouldRetry = AgentChatRuntime.shouldRetryCodexWithFreshThread(
            previousConversationSessionID: "thread_123",
            appServerText: "Codex app-server failed: cannot resume closed thread (404)"
        )
        #expect(shouldRetry)
    }

    @Test("Does not retry when no prior conversation session exists")
    func noRetryWithoutPriorSession() {
        let shouldRetry = AgentChatRuntime.shouldRetryCodexWithFreshThread(
            previousConversationSessionID: nil,
            appServerText: "Codex app-server failed: thread not found"
        )
        #expect(!shouldRetry)
    }

    @Test("Does not retry generic non-thread failures")
    func noRetryForGenericFailure() {
        let shouldRetry = AgentChatRuntime.shouldRetryCodexWithFreshThread(
            previousConversationSessionID: "thread_123",
            appServerText: "Codex app-server failed: context window exceeded"
        )
        #expect(!shouldRetry)
    }

    @Test("Does not retry approval-block failures")
    func noRetryForApprovalBlock() {
        let shouldRetry = AgentChatRuntime.shouldRetryCodexWithFreshThread(
            previousConversationSessionID: "thread_123",
            appServerText: "Codex app-server failed: Blocked: Codex requested approval for network access."
        )
        #expect(!shouldRetry)
    }
}

// MARK: - PullRequestLookupState

@Suite("PullRequestLookupState")
struct PullRequestLookupStateTests {

    @Test("Unavailable lookup drops PR info when confirmed branch is unknown")
    func unavailableDropsInfoWhenConfirmedBranchIsUnknown() throws {
        let url = try #require(URL(string: "https://example.com/pulls/42"))
        let info = PullRequestInfo(number: 42, url: url, provider: .github)
        let state = PullRequestLookupState(info: info, status: .found)

        let next = state.applying(.unavailable, branch: "feature")

        #expect(next.info == nil)
        #expect(next.status == .unavailable)
    }

    @Test("Unavailable lookup preserves info for the same confirmed branch")
    func unavailablePreservesInfoForSameBranch() throws {
        let url = try #require(URL(string: "https://example.com/pulls/42"))
        let info = PullRequestInfo(number: 42, url: url, provider: .github)
        let state = PullRequestLookupState(info: info, status: .found, confirmedBranch: "feature")

        let next = state.applying(.unavailable, branch: "feature")

        #expect(next.info == info)
        #expect(next.confirmedBranch == "feature")
        #expect(next.status == .unavailable)
    }

    @Test("Confirmed not found clears PR info")
    func notFoundClearsInfo() throws {
        let url = try #require(URL(string: "https://example.com/pulls/42"))
        let info = PullRequestInfo(number: 42, url: url, provider: .github)
        let state = PullRequestLookupState(info: info, status: .found, confirmedBranch: "feature")

        let next = state.applying(.notFound, branch: "feature")

        #expect(next.info == nil)
        #expect(next.confirmedBranch == nil)
        #expect(next.status == .notFound)
    }

    @Test("Successful lookup replaces stale info and clears stale status")
    func foundReplacesStaleInfo() throws {
        let oldURL = try #require(URL(string: "https://example.com/pulls/42"))
        let newURL = try #require(URL(string: "https://example.com/pulls/43"))
        let oldInfo = PullRequestInfo(number: 42, url: oldURL, provider: .github)
        let newInfo = PullRequestInfo(number: 43, url: newURL, provider: .github, reviewDecision: .approved)
        let state = PullRequestLookupState(info: oldInfo, status: .unavailable)

        let next = state.applying(.found(newInfo), branch: "feature")

        #expect(next.info == newInfo)
        #expect(next.confirmedBranch == "feature")
        #expect(next.status == .found)
    }
}

// MARK: - TmuxSessionNaming

@Suite("TmuxSessionNaming")
struct TmuxSessionNamingTests {

    @Test("sanitizeForTmux replaces illegal chars with hyphens and lowercases")
    func sanitize() {
        #expect(TmuxSessionNaming.sanitizeForTmux("My Project!") == "my-project-")
        #expect(TmuxSessionNaming.sanitizeForTmux("already_ok-123") == "already_ok-123")
        #expect(TmuxSessionNaming.sanitizeForTmux("a/b:c.d") == "a-b-c-d")
    }

    @Test("repoSlug truncates to 16 chars and trims trailing hyphens")
    func repoSlugTruncation() {
        let long = "thisisaveryverylongproject"
        let slug = TmuxSessionNaming.repoSlug(from: long)
        #expect(slug.count <= 16)
        #expect(slug == "thisisaveryveryl")

        // Trailing hyphens after truncation should be stripped
        let awkward = "short-name-extra-extra"
        let slug2 = TmuxSessionNaming.repoSlug(from: awkward)
        #expect(!slug2.hasSuffix("-"))
    }

    @Test("buildSessionName assembles ma-<repo>-<thread>[-<tab>]")
    func buildSessionName() {
        #expect(TmuxSessionNaming.buildSessionName(repoSlug: "repo", threadName: nil) == "ma-repo")
        #expect(TmuxSessionNaming.buildSessionName(repoSlug: "repo", threadName: "pikachu") == "ma-repo-pikachu")
        #expect(TmuxSessionNaming.buildSessionName(repoSlug: "repo", threadName: "pikachu", tabSlug: "2") == "ma-repo-pikachu-2")
    }

    @Test("isMagentSession accepts ma- and magent- prefixes only")
    func isMagentSession() {
        #expect(TmuxSessionNaming.isMagentSession("ma-repo-thread"))
        #expect(TmuxSessionNaming.isMagentSession("magent-foo"))
        #expect(!TmuxSessionNaming.isMagentSession("mysession"))
        #expect(!TmuxSessionNaming.isMagentSession("map-"))
    }

    @Test("defaultTabDisplayName returns base for each agent type")
    func defaultBase() {
        #expect(TmuxSessionNaming.defaultTabDisplayName(for: .claude) == "Claude")
        #expect(TmuxSessionNaming.defaultTabDisplayName(for: .codex) == "Codex")
        #expect(TmuxSessionNaming.defaultTabDisplayName(for: .custom) == "Custom")
        #expect(TmuxSessionNaming.defaultTabDisplayName(for: nil) == "Terminal")
    }

    @Test("Claude tab name includes model label verbatim")
    func claudeWithModel() {
        let name = TmuxSessionNaming.defaultTabDisplayName(for: .claude, modelLabel: "Sonnet 4.6")
        #expect(name == "Claude (Sonnet 4.6)")
    }

    @Test("Claude tab name includes reasoning level abbreviation")
    func claudeWithEffort() {
        #expect(TmuxSessionNaming.defaultTabDisplayName(for: .claude, reasoningLevel: "high") == "Claude (H)")
        #expect(TmuxSessionNaming.defaultTabDisplayName(for: .claude, reasoningLevel: "medium") == "Claude (M)")
        #expect(TmuxSessionNaming.defaultTabDisplayName(for: .claude, reasoningLevel: "xhigh") == "Claude (xH)")
        #expect(TmuxSessionNaming.defaultTabDisplayName(for: .claude, reasoningLevel: "max") == "Claude (Max)")
    }

    @Test("Claude combines model and effort with comma")
    func claudeCombined() {
        let name = TmuxSessionNaming.defaultTabDisplayName(for: .claude, modelLabel: "Sonnet 4.6", reasoningLevel: "high")
        #expect(name == "Claude (Sonnet 4.6, H)")
    }

    @Test("Codex strips GPT prefix and hyphenates tokens")
    func codexModel() {
        let name = TmuxSessionNaming.defaultTabDisplayName(for: .codex, modelLabel: "GPT 5.3 Codex")
        #expect(name == "Codex (5.3-codex)")
    }

    @Test("Codex formats GPT 5.5 as compact version label")
    func codex55Model() {
        let name = TmuxSessionNaming.defaultTabDisplayName(for: .codex, modelLabel: "GPT 5.5")
        #expect(name == "Codex (5.5)")
    }

    @Test("GPT 5.6 Codex models expose expanded reasoning levels")
    func codex56ReasoningOverrides() {
        let config = AgentModelConfig(
            models: [
                AgentModel(id: "gpt-5.6-sol", label: "GPT 5.6 Sol", reasoningLevels: ["none", "low", "medium", "high", "xhigh", "max"]),
                AgentModel(id: "gpt-5.5", label: "GPT 5.5"),
            ],
            reasoningLevels: ["low", "medium", "high", "xhigh"]
        )

        #expect(config.effectiveReasoningLevels(for: "gpt-5.6-sol") == ["none", "low", "medium", "high", "xhigh", "max"])
        #expect(config.effectiveReasoningLevels(for: "gpt-5.5") == ["low", "medium", "high", "xhigh"])
    }

    @Test("Codex collapses multiple spaces and trims")
    func codexCollapse() {
        let name = TmuxSessionNaming.defaultTabDisplayName(for: .codex, modelLabel: "  gpt   5.4-mini  ")
        #expect(name == "Codex (5.4-mini)")
    }

    @Test("Empty/whitespace model label is ignored")
    func emptyModelIgnored() {
        #expect(TmuxSessionNaming.defaultTabDisplayName(for: .claude, modelLabel: "   ") == "Claude")
        #expect(TmuxSessionNaming.defaultTabDisplayName(for: .claude, modelLabel: nil) == "Claude")
    }

    @Test("Custom agent ignores model label")
    func customIgnoresModel() {
        #expect(TmuxSessionNaming.defaultTabDisplayName(for: .custom, modelLabel: "whatever") == "Custom")
    }

    @Test("looksLikeDefaultTabName matches exact base")
    func looksLikeBase() {
        #expect(TmuxSessionNaming.looksLikeDefaultTabName("Claude", for: .claude))
        #expect(TmuxSessionNaming.looksLikeDefaultTabName("Codex", for: .codex))
        #expect(TmuxSessionNaming.looksLikeDefaultTabName("Terminal", for: nil))
    }

    @Test("looksLikeDefaultTabName matches base with valid parenthesised detail")
    func looksLikeWithDetail() {
        #expect(TmuxSessionNaming.looksLikeDefaultTabName("Claude (M)", for: .claude))
        #expect(TmuxSessionNaming.looksLikeDefaultTabName("Claude (Sonnet 4.6)", for: .claude))
        #expect(TmuxSessionNaming.looksLikeDefaultTabName("Claude (Sonnet 4.6, H)", for: .claude))
        #expect(TmuxSessionNaming.looksLikeDefaultTabName("Codex (5.3-codex)", for: .codex))
    }

    @Test("looksLikeDefaultTabName rejects human-meaningful names")
    func looksLikeRejects() {
        #expect(!TmuxSessionNaming.looksLikeDefaultTabName("My Debug Tab", for: .claude))
        #expect(!TmuxSessionNaming.looksLikeDefaultTabName("Claude (my notes!)", for: .claude))
        #expect(!TmuxSessionNaming.looksLikeDefaultTabName("Claude ()", for: .claude))
        // Wrong base
        #expect(!TmuxSessionNaming.looksLikeDefaultTabName("Codex (M)", for: .claude))
    }

    @Test("renamedSessionName rewrites prefix for exact match")
    func renameExact() {
        let renamed = TmuxSessionNaming.renamedSessionName(
            "ma-repo-oldname",
            fromThreadName: "oldname",
            toThreadName: "newname",
            repoSlug: "repo"
        )
        #expect(renamed == "ma-repo-newname")
    }

    @Test("renamedSessionName rewrites prefix while preserving tab suffix")
    func renameWithTab() {
        let renamed = TmuxSessionNaming.renamedSessionName(
            "ma-repo-oldname-tab-2",
            fromThreadName: "oldname",
            toThreadName: "newname",
            repoSlug: "repo"
        )
        #expect(renamed == "ma-repo-newname-tab-2")
    }

    @Test("renamedSessionName leaves unrelated sessions untouched")
    func renameUnrelated() {
        let renamed = TmuxSessionNaming.renamedSessionName(
            "ma-repo-otherthread",
            fromThreadName: "oldname",
            toThreadName: "newname",
            repoSlug: "repo"
        )
        #expect(renamed == "ma-repo-otherthread")
    }

    @Test("renamedSessionName must not match as substring of a longer thread name")
    func renameBoundary() {
        // "ma-repo-oldnameextra" shouldn't be rewritten when renaming "oldname"
        let renamed = TmuxSessionNaming.renamedSessionName(
            "ma-repo-oldnameextra",
            fromThreadName: "oldname",
            toThreadName: "newname",
            repoSlug: "repo"
        )
        #expect(renamed == "ma-repo-oldnameextra")
    }
}

// MARK: - GitRemote parsing

@Suite("GitRemote.parse URL handling")
struct GitRemoteParseTests {

    @Test("Parses SSH shorthand git@host:owner/repo.git")
    func sshShorthand() throws {
        let remote = try #require(GitRemote.parse(name: "origin", rawURL: "git@github.com:owner/repo.git"))
        #expect(remote.host == "github.com")
        #expect(remote.repoPath == "owner/repo")
        #expect(remote.provider == .github)
    }

    @Test("Parses https URLs and strips .git suffix")
    func https() throws {
        let remote = try #require(GitRemote.parse(name: "origin", rawURL: "https://gitlab.com/group/sub/repo.git"))
        #expect(remote.host == "gitlab.com")
        #expect(remote.repoPath == "group/sub/repo")
        #expect(remote.provider == .gitlab)
    }

    @Test("Parses ssh:// URLs with user and port")
    func sshWithPort() throws {
        let remote = try #require(GitRemote.parse(name: "origin", rawURL: "ssh://git@bitbucket.org:7999/team/repo.git"))
        #expect(remote.host == "bitbucket.org")
        #expect(remote.repoPath == "team/repo")
        #expect(remote.provider == .bitbucket)
    }

    @Test("Detects unknown provider for unfamiliar hosts")
    func unknownProvider() throws {
        let remote = try #require(GitRemote.parse(name: "origin", rawURL: "https://git.example.com/owner/repo.git"))
        #expect(remote.provider == .unknown)
    }

    @Test("Returns nil when path is missing")
    func missingPath() {
        #expect(GitRemote.parse(name: "origin", rawURL: "https://github.com") == nil)
        #expect(GitRemote.parse(name: "origin", rawURL: "") == nil)
    }

    @Test("Keeps path when no .git suffix is present")
    func noGitSuffix() throws {
        let remote = try #require(GitRemote.parse(name: "origin", rawURL: "https://github.com/owner/repo"))
        #expect(remote.repoPath == "owner/repo")
    }
}

// MARK: - GitRemote URL builders

@Suite("GitRemote PR URL builders")
struct GitRemotePullRequestURLTests {

    let github = GitRemote.parse(name: "origin", rawURL: "https://github.com/owner/repo.git")!
    let gitlab = GitRemote.parse(name: "origin", rawURL: "https://gitlab.com/group/repo.git")!
    let bitbucket = GitRemote.parse(name: "origin", rawURL: "https://bitbucket.org/team/repo.git")!
    let unknown = GitRemote.parse(name: "origin", rawURL: "https://git.example.com/o/r.git")!

    @Test("Default branch returns open PRs listing")
    func defaultBranchGoesToListing() {
        let url = github.pullRequestURL(for: "main", defaultBranch: "main")
        #expect(url?.absoluteString == "https://github.com/owner/repo/pulls?q=is%3Aopen+is%3Apr")
    }

    @Test("Branch-specific URL for GitHub includes head:<branch> query")
    func githubBranchQuery() {
        let url = github.pullRequestURL(for: "feature x", defaultBranch: "main")
        let encoded = url?.absoluteString ?? ""
        // urlQueryAllowed encodes spaces but not '/', matching GitHub's expected query format.
        #expect(encoded.contains("head%3Afeature%20x"))
    }

    @Test("GitLab uses source_branch query")
    func gitlabBranchQuery() {
        let url = gitlab.pullRequestURL(for: "feature", defaultBranch: "main")
        #expect(url?.absoluteString.contains("source_branch=feature") == true)
        #expect(url?.absoluteString.contains("state=opened") == true)
    }

    @Test("Bitbucket uses source query and state=OPEN")
    func bitbucketBranchQuery() {
        let url = bitbucket.pullRequestURL(for: "feature", defaultBranch: "main")
        #expect(url?.absoluteString.contains("source=feature") == true)
        #expect(url?.absoluteString.contains("state=OPEN") == true)
    }

    @Test("createPullRequestURL requires non-empty source")
    func createPRRequiresSource() {
        #expect(github.createPullRequestURL(sourceBranch: "   ", targetBranch: "main") == nil)
    }

    @Test("GitHub createPullRequestURL requires target and uses compare path")
    func createPRGitHub() throws {
        let url = try #require(github.createPullRequestURL(sourceBranch: "feature", targetBranch: "main", title: "My PR"))
        #expect(url.absoluteString.hasPrefix("https://github.com/owner/repo/compare/main...feature"))
        #expect(url.absoluteString.contains("expand=1"))
        #expect(url.absoluteString.contains("title=My%20PR"))

        #expect(github.createPullRequestURL(sourceBranch: "feature", targetBranch: nil) == nil)
    }

    @Test("GitLab createPullRequestURL builds merge_request form")
    func createPRGitLab() throws {
        let url = try #require(gitlab.createPullRequestURL(sourceBranch: "feature", targetBranch: "main", title: "t"))
        let s = url.absoluteString
        #expect(s.contains("merge_request%5Bsource_branch%5D=feature"))
        #expect(s.contains("merge_request%5Btarget_branch%5D=main"))
        #expect(s.contains("merge_request%5Btitle%5D=t"))
    }

    @Test("Bitbucket createPullRequestURL requires target")
    func createPRBitbucket() throws {
        #expect(bitbucket.createPullRequestURL(sourceBranch: "feature", targetBranch: nil) == nil)
        let url = try #require(bitbucket.createPullRequestURL(sourceBranch: "feature", targetBranch: "main"))
        let s = url.absoluteString
        #expect(s.contains("source=feature"))
        #expect(s.contains("dest=main"))
    }

    @Test("Unknown provider returns nil for createPullRequestURL")
    func createPRUnknown() {
        #expect(unknown.createPullRequestURL(sourceBranch: "feature", targetBranch: "main") == nil)
    }

    @Test("directPullRequestURL varies by provider")
    func directURLs() {
        #expect(github.directPullRequestURL(number: 42)?.absoluteString == "https://github.com/owner/repo/pull/42")
        #expect(gitlab.directPullRequestURL(number: 42)?.absoluteString == "https://gitlab.com/group/repo/-/merge_requests/42")
        #expect(bitbucket.directPullRequestURL(number: 42)?.absoluteString == "https://bitbucket.org/team/repo/pull-requests/42")
        #expect(unknown.directPullRequestURL(number: 42) == nil)
    }
}

// MARK: - BranchUpstreamStatus

@Suite("BranchUpstreamStatus display text")
struct BranchUpstreamStatusTests {

    @Test("Local branch has (local) suffix")
    func localBranch() {
        let s = BranchUpstreamStatus(upstreamRef: nil, aheadCount: nil, behindCount: nil)
        #expect(s.inlineSuffix == "(local)")
        #expect(s.displayText == "Local")
        #expect(s.displayUpstreamRef == nil)
        #expect(s.tooltipText == "This branch has no configured remote counterpart.")
    }

    @Test("Up-to-date returns nil inline suffix")
    func upToDate() {
        let s = BranchUpstreamStatus(upstreamRef: "origin/main", aheadCount: 0, behindCount: 0)
        #expect(s.inlineSuffix == nil)
        #expect(s.displayText == "Up to date with remote")
        #expect(s.tooltipText == "Upstream: main")
    }

    @Test("Ahead-only uses + count")
    func aheadOnly() {
        let s = BranchUpstreamStatus(upstreamRef: "origin/main", aheadCount: 3, behindCount: 0)
        #expect(s.inlineSuffix == "(+3 from remote)")
        #expect(s.tooltipText == "Upstream: main (3 ahead)")
    }

    @Test("Behind-only uses - count")
    func behindOnly() {
        let s = BranchUpstreamStatus(upstreamRef: "origin/main", aheadCount: 0, behindCount: 5)
        #expect(s.inlineSuffix == "(-5 from remote)")
        #expect(s.tooltipText == "Upstream: main (5 behind)")
    }

    @Test("Both ahead and behind")
    func both() {
        let s = BranchUpstreamStatus(upstreamRef: "origin/main", aheadCount: 2, behindCount: 4)
        #expect(s.inlineSuffix == "(+2 -4 from remote)")
        #expect(s.tooltipText == "Upstream: main (2 ahead, 4 behind)")
    }

    @Test("Negative/nil counts treated as zero")
    func clampsNegatives() {
        let s = BranchUpstreamStatus(upstreamRef: "origin/main", aheadCount: -1, behindCount: nil)
        #expect(s.inlineSuffix == nil) // both clamp to 0
    }

    @Test("displayUpstreamRef strips origin/ prefix but preserves others")
    func displayUpstreamRef() {
        #expect(BranchUpstreamStatus(upstreamRef: "origin/main").displayUpstreamRef == "main")
        #expect(BranchUpstreamStatus(upstreamRef: "upstream/dev").displayUpstreamRef == "upstream/dev")
    }
}

// MARK: - AppSettings helpers

@Suite("AppSettings static helpers")
struct AppSettingsStaticHelperTests {

    @Test("parseJiraTicketDetectionPrefixes splits on comma/semicolon/newline")
    func splitsDelimiters() {
        let result = AppSettings.parseJiraTicketDetectionPrefixes("ABC, def;GHI\njkl")
        #expect(result == ["ABC", "DEF", "GHI", "JKL"])
    }

    @Test("Trims whitespace and leading/trailing dashes")
    func trimsDashes() {
        let result = AppSettings.parseJiraTicketDetectionPrefixes("  -ABC-  , DEF--")
        #expect(result == ["ABC", "DEF"])
    }

    @Test("Drops empty entries")
    func dropsEmpty() {
        let result = AppSettings.parseJiraTicketDetectionPrefixes(",,  ,ABC,,,")
        #expect(result == ["ABC"])
    }

    @Test("Preserves input order")
    func preservesOrder() {
        let result = AppSettings.parseJiraTicketDetectionPrefixes("zzz, aaa, mmm")
        #expect(result == ["ZZZ", "AAA", "MMM"])
    }
}

// MARK: - AppSettings.command(for:)

@Suite("AppSettings.command(for:)")
struct AppSettingsCommandTests {

    private func settings(skipPermissions: Bool = false, sandboxEnabled: Bool = false, custom: String = "") -> AppSettings {
        AppSettings(
            activeAgents: [.claude, .codex, .custom],
            customAgentCommand: custom,
            agentSandboxEnabled: sandboxEnabled,
            agentSkipPermissions: skipPermissions
        )
    }

    @Test("Claude picks unrestricted bypass, sandbox auto, or no-flag ask mode")
    func claudeCommand() {
        #expect(settings(skipPermissions: false, sandboxEnabled: true).command(for: .claude) == "command claude --permission-mode auto")
        #expect(settings(skipPermissions: true).command(for: .claude) == "command claude --dangerously-skip-permissions")
        #expect(settings(skipPermissions: false, sandboxEnabled: false).command(for: .claude) == "command claude")
    }

    @Test("Codex picks --yolo, --full-auto, or no-flag ask mode")
    func codexCommand() {
        #expect(settings(skipPermissions: true, sandboxEnabled: false).command(for: .codex) == "command codex --yolo")
        #expect(settings(skipPermissions: false, sandboxEnabled: true).command(for: .codex) == "command codex --full-auto")
        #expect(settings(skipPermissions: false, sandboxEnabled: false).command(for: .codex) == "command codex")
        // Skip-permissions dominates sandbox
        #expect(settings(skipPermissions: true, sandboxEnabled: true).command(for: .codex) == "command codex --yolo")
    }

    @Test("agentPermissionMode normalizes legacy boolean combinations")
    func permissionModeCompatibilityMapping() {
        #expect(settings(skipPermissions: false, sandboxEnabled: true).agentPermissionMode == .sandboxAuto)
        #expect(settings(skipPermissions: true, sandboxEnabled: false).agentPermissionMode == .unrestricted)
        #expect(settings(skipPermissions: false, sandboxEnabled: false).agentPermissionMode == .askEveryTime)
        #expect(settings(skipPermissions: true, sandboxEnabled: true).agentPermissionMode == .unrestricted)
    }

    @Test("Custom uses configured command, fallback when blank")
    func customCommand() {
        #expect(settings(custom: "").command(for: .custom) == "custom-agent")
        #expect(settings(custom: "   ").command(for: .custom) == "custom-agent")
        #expect(settings(custom: " my-tool --flag ").command(for: .custom) == "my-tool --flag")
    }
}

// MARK: - AppSettings.effectiveGlobalDefaultAgentType

@Suite("AppSettings.effectiveGlobalDefaultAgentType")
struct AppSettingsDefaultAgentTests {

    @Test("Nil when no active agents")
    func emptyActive() {
        let s = AppSettings(activeAgents: [])
        #expect(s.effectiveGlobalDefaultAgentType == nil)
    }

    @Test("Single active agent wins regardless of defaultAgentType")
    func single() {
        let s = AppSettings(activeAgents: [.codex], defaultAgentType: .claude)
        #expect(s.effectiveGlobalDefaultAgentType == .codex)
    }

    @Test("Uses defaultAgentType when it is among active agents")
    func usesDefault() {
        let s = AppSettings(activeAgents: [.claude, .codex], defaultAgentType: .codex)
        #expect(s.effectiveGlobalDefaultAgentType == .codex)
    }

    @Test("Falls back to first active when default is not available")
    func fallback() {
        let s = AppSettings(activeAgents: [.claude, .codex], defaultAgentType: .custom)
        #expect(s.effectiveGlobalDefaultAgentType == .claude)
    }

    @Test("availableActiveAgents de-duplicates while preserving order")
    func dedupe() {
        let s = AppSettings(activeAgents: [.claude, .codex, .claude, .custom, .codex])
        let available = s.availableActiveAgents
        #expect(s.effectiveGlobalDefaultAgentType == .claude)
        #expect(available == [.claude, .codex, .custom])
    }
}

// MARK: - AppSettings status bar thread statuses

@Suite("AppSettings status bar thread statuses")
struct AppSettingsStatusBarThreadStatusTests {

    @Test("Default expanded status bar statuses match the legacy inline groups")
    func defaultExpandedStatuses() {
        #expect(AppSettings().expandedStatusBarThreadStatuses == [.favorites, .done, .waiting])
    }

    @Test("Expanded status bar statuses normalize to fixed display order")
    func normalizesExpandedStatusOrder() {
        let settings = AppSettings(expandedStatusBarThreadStatuses: [.rateLimited, .busy, .favorites, .busy])

        #expect(settings.expandedStatusBarThreadStatuses == [.favorites, .busy, .rateLimited])
    }

    @Test("Missing expanded status bar settings decode to the legacy default")
    func decodesMissingExpandedStatusesToDefault() throws {
        let baselineData = try JSONEncoder().encode(AppSettings())
        var baselineObject = try #require(JSONSerialization.jsonObject(with: baselineData) as? [String: Any])
        baselineObject.removeValue(forKey: "expandedStatusBarThreadStatuses")
        let data = try JSONSerialization.data(withJSONObject: baselineObject)

        let decoded = try JSONDecoder().decode(AppSettings.self, from: data)

        #expect(decoded.expandedStatusBarThreadStatuses == [.favorites, .done, .waiting])
    }
}

// MARK: - AppSettings thread row width

@Suite("AppSettings thread row width")
struct AppSettingsThreadRowWidthTests {

    @Test("New settings default to narrow thread rows")
    func defaultsToNarrowThreadRows() {
        let settings = AppSettings()

        #expect(!settings.wideThreads)
        #expect(settings.sidebarDescriptionLineLimit == 1)
    }

    @Test("Wide thread rows allow two description lines")
    func wideThreadRowsAllowTwoDescriptionLines() {
        let settings = AppSettings(wideThreads: true)

        #expect(settings.sidebarDescriptionLineLimit == 2)
    }

    @Test("Legacy narrow thread setting migrates by inversion")
    func legacyNarrowThreadsMigratesByInversion() throws {
        let baselineData = try JSONEncoder().encode(AppSettings())
        var baselineObject = try #require(JSONSerialization.jsonObject(with: baselineData) as? [String: Any])

        baselineObject.removeValue(forKey: "wideThreads")
        baselineObject["narrowThreads"] = true
        let narrowData = try JSONSerialization.data(withJSONObject: baselineObject)
        let migratedFromNarrow = try JSONDecoder().decode(AppSettings.self, from: narrowData)

        baselineObject["narrowThreads"] = false
        let wideData = try JSONSerialization.data(withJSONObject: baselineObject)
        let migratedFromWide = try JSONDecoder().decode(AppSettings.self, from: wideData)

        #expect(!migratedFromNarrow.wideThreads)
        #expect(migratedFromNarrow.sidebarDescriptionLineLimit == 1)
        #expect(migratedFromWide.wideThreads)
        #expect(migratedFromWide.sidebarDescriptionLineLimit == 2)
    }

    @Test("Wide thread setting round-trips under the new key")
    func wideThreadsRoundTripsUnderNewKey() throws {
        let data = try JSONEncoder().encode(AppSettings(wideThreads: true))
        let object = try #require(JSONSerialization.jsonObject(with: data) as? [String: Any])
        let decoded = try JSONDecoder().decode(AppSettings.self, from: data)

        #expect(object["wideThreads"] as? Bool == true)
        #expect(object["narrowThreads"] == nil)
        #expect(decoded.wideThreads)
    }
}

// MARK: - AppSettings thread icons

@Suite("AppSettings thread icons")
struct AppSettingsThreadIconVisibilityTests {

    @Test("New settings show thread icons by default")
    func defaultsToShowingThreadIcons() {
        #expect(AppSettings().showThreadIcons)
    }

    @Test("Existing settings without thread icon visibility migrate to hidden")
    func decodesMissingThreadIconVisibilityToHidden() throws {
        let baselineData = try JSONEncoder().encode(AppSettings())
        var baselineObject = try #require(JSONSerialization.jsonObject(with: baselineData) as? [String: Any])
        baselineObject.removeValue(forKey: "showThreadIcons")
        let data = try JSONSerialization.data(withJSONObject: baselineObject)

        let decoded = try JSONDecoder().decode(AppSettings.self, from: data)

        #expect(!decoded.showThreadIcons)
    }

    @Test("Explicit thread icon visibility setting round-trips", arguments: [true, false])
    func threadIconVisibilityRoundTrips(showThreadIcons: Bool) throws {
        let data = try JSONEncoder().encode(AppSettings(showThreadIcons: showThreadIcons))
        let object = try #require(JSONSerialization.jsonObject(with: data) as? [String: Any])
        let decoded = try JSONDecoder().decode(AppSettings.self, from: data)

        #expect(object["showThreadIcons"] as? Bool == showThreadIcons)
        #expect(decoded.showThreadIcons == showThreadIcons)
    }
}

// MARK: - AppSettings terminal surface cache

@Suite("AppSettings terminal surface cache")
struct AppSettingsTerminalSurfaceCacheTests {

    @Test("Default cache limit is finite")
    func defaultCacheLimit() {
        #expect(AppSettings().terminalSurfaceCacheLimit == AppSettings.defaultTerminalSurfaceCacheLimit)
    }

    @Test("Missing cache limit decodes to default for older settings files")
    func missingCacheLimitDecodesToDefault() throws {
        let baselineData = try JSONEncoder().encode(AppSettings())
        var baselineObject = try #require(JSONSerialization.jsonObject(with: baselineData) as? [String: Any])
        baselineObject.removeValue(forKey: "terminalSurfaceCacheLimit")
        let data = try JSONSerialization.data(withJSONObject: baselineObject)

        let decoded = try JSONDecoder().decode(AppSettings.self, from: data)

        #expect(decoded.terminalSurfaceCacheLimit == AppSettings.defaultTerminalSurfaceCacheLimit)
    }

    @Test("Nil cache limit round-trips as unlimited")
    func nilCacheLimitRoundTripsAsUnlimited() throws {
        let original = AppSettings(terminalSurfaceCacheLimit: nil)

        let data = try JSONEncoder().encode(original)
        let decodedObject = try #require(JSONSerialization.jsonObject(with: data) as? [String: Any])
        let decoded = try JSONDecoder().decode(AppSettings.self, from: data)

        #expect(decodedObject.keys.contains("terminalSurfaceCacheLimit"))
        #expect(decoded.terminalSurfaceCacheLimit == nil)
    }

    @Test("Cache limit is clamped to supported range")
    func cacheLimitClampsToSupportedRange() throws {
        #expect(AppSettings(terminalSurfaceCacheLimit: -10).terminalSurfaceCacheLimit == AppSettings.minTerminalSurfaceCacheLimit)
        #expect(AppSettings(terminalSurfaceCacheLimit: 1_000).terminalSurfaceCacheLimit == AppSettings.maxTerminalSurfaceCacheLimit)
    }
}

// MARK: - AppSettings chat appearance fields

@Suite("AppSettings chat appearance fields")
struct AppSettingsChatAppearanceTests {

    @Test("Defaults stay nil when custom chat colors are not set")
    func defaultsNil() throws {
        let data = try JSONEncoder().encode(AppSettings())
        let decoded = try JSONDecoder().decode(AppSettings.self, from: data)
        #expect(decoded.chatUserBubbleColorHex == nil)
        #expect(decoded.chatUserTextColorHex == nil)
        #expect(decoded.chatAssistantBubbleColorHex == nil)
        #expect(decoded.chatAssistantTextColorHex == nil)
    }

    @Test("Round-trip preserves custom chat color hex values")
    func roundTripCustomValues() throws {
        let original = AppSettings(
            chatUserBubbleColorHex: "#112233",
            chatUserTextColorHex: "#445566",
            chatAssistantBubbleColorHex: "#778899",
            chatAssistantTextColorHex: "#AABBCC"
        )
        let data = try JSONEncoder().encode(original)
        let decoded = try JSONDecoder().decode(AppSettings.self, from: data)
        #expect(decoded.chatUserBubbleColorHex == "#112233")
        #expect(decoded.chatUserTextColorHex == "#445566")
        #expect(decoded.chatAssistantBubbleColorHex == "#778899")
        #expect(decoded.chatAssistantTextColorHex == "#AABBCC")
    }

    @Test("Chat font size defaults to AppSettings default value")
    func defaultChatFontSize() throws {
        let data = try JSONEncoder().encode(AppSettings())
        let decoded = try JSONDecoder().decode(AppSettings.self, from: data)
        #expect(decoded.chatFontSize == AppSettings.defaultChatFontSize)
    }

    @Test("Chat font size is clamped when decoding out-of-range values")
    func clampedDecodedChatFontSize() throws {
        let baselineData = try JSONEncoder().encode(AppSettings())
        let baselineObject = try #require(JSONSerialization.jsonObject(with: baselineData) as? [String: Any])

        var lowObject = baselineObject
        lowObject["chatFontSize"] = 4
        let lowData = try JSONSerialization.data(withJSONObject: lowObject)
        let tooSmall = try JSONDecoder().decode(
            AppSettings.self,
            from: lowData
        )
        #expect(tooSmall.chatFontSize == AppSettings.minChatFontSize)

        var highObject = baselineObject
        highObject["chatFontSize"] = 100
        let highData = try JSONSerialization.data(withJSONObject: highObject)
        let tooLarge = try JSONDecoder().decode(
            AppSettings.self,
            from: highData
        )
        #expect(tooLarge.chatFontSize == AppSettings.maxChatFontSize)
    }

    @Test("Experimental chats default off and round-trip through settings")
    func experimentalChatsDefaultAndRoundTrip() throws {
        let defaultSettings = AppSettings()
        #expect(!defaultSettings.experimentalEnableChats)

        let original = AppSettings(experimentalEnableChats: true)
        let data = try JSONEncoder().encode(original)
        let decoded = try JSONDecoder().decode(AppSettings.self, from: data)
        #expect(decoded.experimentalEnableChats)
    }

    @Test("Chats feature gate follows debug-only experimental setting")
    func chatsFeatureGate() {
        #if DEBUG
        #expect(!AppSettings().isChatsFeatureEnabled)
        #expect(AppSettings(experimentalEnableChats: true).isChatsFeatureEnabled)
        #else
        #expect(!AppSettings(experimentalEnableChats: true).isChatsFeatureEnabled)
        #endif
    }

    @Test("Chat settings category follows chats feature gate")
    func chatSettingsCategoryGate() {
        #if DEBUG
        #expect(!AppSettings().shouldShowChatSettingsCategory)
        #expect(AppSettings(experimentalEnableChats: true).shouldShowChatSettingsCategory)
        #else
        #expect(!AppSettings(experimentalEnableChats: true).shouldShowChatSettingsCategory)
        #endif
    }
}

// MARK: - AgentType.capabilities

@Suite("AgentType.capabilities")
struct AgentTypeCapabilitiesTests {

    @Test("Claude and Codex expose terminal and chat surfaces")
    func claudeAndCodexPrimaryTier() {
        for agent in [AgentType.claude, .codex] {
            let capabilities = agent.capabilities
            #expect(capabilities.supportedSurfaces == [.terminal, .chat])
            #expect(capabilities.defaultSurface == .terminal)
            #expect(capabilities.supportsResume)
            #expect(capabilities.supportsModelSelection)
            #expect(capabilities.supportsReasoningSelection)
            #expect(capabilities.supportsInitialPromptInjection)
            #expect(capabilities.supportsIPCSystemPromptInjection)
            #expect(capabilities.supportsDirectoryTrustBootstrap)
            #expect(capabilities.supportsOutputRateLimitDetection)
            #expect(!capabilities.supportsStructuredRateLimitSignals)

            #expect(agent.supportedSurfaces == [.terminal, .chat])
            #expect(agent.defaultSurface == .terminal)
            #expect(agent.supportsResume)
        }
    }

    @Test("Custom stays intentionally partial")
    func customPartialTier() {
        let capabilities = AgentType.custom.capabilities
        #expect(capabilities.supportedSurfaces == [.terminal])
        #expect(capabilities.defaultSurface == .terminal)
        #expect(!capabilities.supportsResume)
        #expect(!capabilities.supportsModelSelection)
        #expect(!capabilities.supportsReasoningSelection)
        #expect(capabilities.supportsInitialPromptInjection)
        #expect(!capabilities.supportsIPCSystemPromptInjection)
        #expect(!capabilities.supportsDirectoryTrustBootstrap)
        #expect(!capabilities.supportsOutputRateLimitDetection)
        #expect(!capabilities.supportsStructuredRateLimitSignals)

        #expect(AgentType.custom.supportedSurfaces == [.terminal])
        #expect(AgentType.custom.defaultSurface == .terminal)
        #expect(!AgentType.custom.supportsResume)
    }

    @Test("Surface display names add suffix only for multi-surface agents")
    func surfaceDisplayNames() {
        #expect(AgentType.claude.displayName(for: .terminal) == "Claude Code (Terminal)")
        #expect(AgentType.claude.displayName(for: .chat) == "Claude Code (Chat)")
        #expect(AgentType.codex.displayName(for: .terminal) == "Codex (Terminal)")
        #expect(AgentType.custom.displayName(for: .terminal) == "Custom")
    }

    @Test("Chat feature gate collapses visible surfaces and labels")
    func chatFeatureGateSurfacesAndLabels() {
        #expect(AgentType.codex.supportedSurfaces(chatsEnabled: false) == [.terminal])
        #expect(AgentType.codex.displayName(for: .terminal, chatsEnabled: false) == "Codex")

        #expect(AgentType.codex.supportedSurfaces(chatsEnabled: true) == [.terminal, .chat])
        #expect(AgentType.codex.displayName(for: .terminal, chatsEnabled: true) == "Codex (Terminal)")
        #expect(AgentType.codex.displayName(for: .chat, chatsEnabled: true) == "Codex (Chat)")
    }
}

// MARK: - ThreadSection decoding & color

@Suite("ThreadSection")
struct ThreadSectionTests {

    @Test("Decodes with isVisible/isKeepAlive defaults when fields missing")
    func legacyDecode() throws {
        let json = """
        {"id":"11111111-1111-1111-1111-111111111111","name":"Todo","colorHex":"#007AFF","sortOrder":0,"isDefault":true}
        """.data(using: .utf8)!
        let section = try JSONDecoder().decode(ThreadSection.self, from: json)
        #expect(section.isVisible == true)
        #expect(section.isKeepAlive == false)
        #expect(section.name == "Todo")
    }

    @Test("Honors explicit isVisible/isKeepAlive when present")
    func newFieldsDecode() throws {
        let json = """
        {"id":"11111111-1111-1111-1111-111111111111","name":"Hidden","colorHex":"#007AFF","sortOrder":1,"isDefault":false,"isVisible":false,"isKeepAlive":true}
        """.data(using: .utf8)!
        let section = try JSONDecoder().decode(ThreadSection.self, from: json)
        #expect(section.isVisible == false)
        #expect(section.isKeepAlive == true)
    }

    @Test("defaults() returns the four canonical sections")
    func defaults() {
        let defaults = ThreadSection.defaults()
        let names = defaults.map(\.name)
        let orders = defaults.map(\.sortOrder)
        let allDefault = defaults.allSatisfy(\.isDefault)
        #expect(defaults.count == 4)
        #expect(names == ["TODO", "In Progress", "Reviewing", "Done"])
        #expect(allDefault)
        #expect(orders == [0, 1, 2, 3])
    }

    @MainActor
    @Test("NSColor(hex:) parses 6-digit values with and without leading #")
    func colorHexValid() {
        #expect(NSColor(hex: "#FF0000") != nil)
        #expect(NSColor(hex: "00ff00") != nil)
        #expect(NSColor(hex: "  #0000ff  ") != nil)

        let red = NSColor(hex: "#FF0000")!.usingColorSpace(.sRGB)!
        var r: CGFloat = 0, g: CGFloat = 0, b: CGFloat = 0, a: CGFloat = 0
        red.getRed(&r, green: &g, blue: &b, alpha: &a)
        #expect(r == 1.0 && g == 0.0 && b == 0.0)
    }

    @MainActor
    @Test("NSColor(hex:) rejects wrong length or non-hex input")
    func colorHexInvalid() {
        #expect(NSColor(hex: "#FFF") == nil) // 3-digit short form not supported
        #expect(NSColor(hex: "#GGGGGG") == nil)
        #expect(NSColor(hex: "") == nil)
        #expect(NSColor(hex: "#1234567") == nil)
    }
}

// MARK: - PersistedChatMessage

@Suite("PersistedChatMessage")
struct PersistedChatMessageTests {

    @Test("Legacy decode without model metadata defaults to nil")
    func legacyDecodeWithoutModelMetadata() throws {
        let json = """
        {"id":"11111111-1111-1111-1111-111111111111","role":"user","text":"hello","createdAt":"2026-01-01T10:00:00Z"}
        """.data(using: .utf8)!
        let decoder = JSONDecoder()
        decoder.dateDecodingStrategy = .iso8601
        let message = try decoder.decode(PersistedChatMessage.self, from: json)
        #expect(message.modelId == nil)
        #expect(message.reasoningLevel == nil)
        #expect(message.attachments.isEmpty)
    }

    @Test("Round-trip preserves model metadata and attachments")
    func roundTripPreservesModelMetadataAndAttachments() throws {
        let attachment = PersistedChatAttachment(
            id: UUID(uuidString: "22222222-2222-2222-2222-222222222222")!,
            filePath: "/tmp/Screenshot 2026-05-22 at 10.49.01.png",
            kind: .image
        )
        let original = PersistedChatMessage(
            role: .assistant,
            text: "done",
            attachments: [attachment],
            createdAt: Date(timeIntervalSince1970: 1_750_000_000),
            modelId: "gpt-5.5",
            reasoningLevel: "high"
        )
        let encoder = JSONEncoder()
        encoder.dateEncodingStrategy = .iso8601
        let data = try encoder.encode(original)

        let decoder = JSONDecoder()
        decoder.dateDecodingStrategy = .iso8601
        let decoded = try decoder.decode(PersistedChatMessage.self, from: data)
        #expect(decoded.modelId == "gpt-5.5")
        #expect(decoded.reasoningLevel == "high")
        #expect(decoded.attachments == [attachment])
    }
}

// MARK: - PersistedDraftTab

@Suite("PersistedDraftTab")
struct PersistedDraftTabTests {

    @Test("Legacy decode defaults isPinned to false")
    func legacyDecodeDefaultsPinnedState() throws {
        let json = """
        {"identifier":"draft:1","agentType":"codex","prompt":"Prompt"}
        """.data(using: .utf8)!
        let tab = try JSONDecoder().decode(PersistedDraftTab.self, from: json)
        #expect(tab.isPinned == false)
    }

    @Test("Round-trip preserves pinned state")
    func roundTripPinnedState() throws {
        let original = PersistedDraftTab(
            identifier: "draft:pinned",
            agentType: .codex,
            prompt: "Prompt",
            isPinned: true
        )
        let data = try JSONEncoder().encode(original)
        let decoded = try JSONDecoder().decode(PersistedDraftTab.self, from: data)
        #expect(decoded.isPinned == true)
    }
}

// MARK: - PersistedChatTab

@Suite("PersistedChatTab")
struct PersistedChatTabTests {

    @Test("Legacy decode without draftInput defaults to empty string")
    func legacyDecodeDefaultsDraftInput() throws {
        let json = """
        {"identifier":"chat:1","agentType":"claude","title":"Chat","messages":[]}
        """.data(using: .utf8)!
        let tab = try JSONDecoder().decode(PersistedChatTab.self, from: json)
        #expect(tab.draftInput == "")
        #expect(tab.draftAttachments.isEmpty)
        #expect(tab.conversationSessionID == nil)
        #expect(tab.isPinned == false)
    }

    @Test("Round-trip preserves non-empty draftInput, conversation session id, and model metadata")
    func roundTripDraftInput() throws {
        let original = PersistedChatTab(
            identifier: "chat:2",
            agentType: .codex,
            title: "Chat",
            messages: [],
            draftInput: "hello draft",
            conversationSessionID: "session-123",
            modelId: "gpt-5.5",
            reasoningLevel: "high",
            isPinned: true
        )
        let data = try JSONEncoder().encode(original)
        let decoded = try JSONDecoder().decode(PersistedChatTab.self, from: data)
        #expect(decoded.draftInput == "hello draft")
        #expect(decoded.conversationSessionID == "session-123")
        #expect(decoded.modelId == "gpt-5.5")
        #expect(decoded.reasoningLevel == "high")
        #expect(decoded.isPinned == true)
    }

    @Test("Round-trip preserves draft attachments")
    func roundTripDraftAttachments() throws {
        let original = PersistedChatTab(
            identifier: "chat:attachments",
            agentType: .codex,
            title: "Chat",
            messages: [],
            draftInput: "",
            draftAttachments: [
                PersistedChatAttachment(filePath: "/tmp/example.png", kind: .image),
                PersistedChatAttachment(filePath: "/tmp/demo.mov", kind: .video),
            ],
            conversationSessionID: nil
        )
        let data = try JSONEncoder().encode(original)
        let decoded = try JSONDecoder().decode(PersistedChatTab.self, from: data)
        #expect(decoded.draftAttachments.count == 2)
        #expect(decoded.draftAttachments[0].kind == .image)
        #expect(decoded.draftAttachments[1].kind == .video)
    }
}

// MARK: - AgentChatRuntime parsing

@Suite("AgentChatRuntime parsing")
struct AgentChatRuntimeParsingTests {

    @Test("Codex permission flags support unrestricted, sandbox-auto, and ask modes")
    func codexPermissionFlagsSelection() {
        #expect(AgentChatRuntime.codexPermissionFlags(skipPermissions: true, sandboxEnabled: false) == ["--yolo"])
        #expect(AgentChatRuntime.codexPermissionFlags(skipPermissions: false, sandboxEnabled: true) == ["--full-auto"])
        #expect(AgentChatRuntime.codexPermissionFlags(skipPermissions: false, sandboxEnabled: false).isEmpty)
        #expect(AgentChatRuntime.codexPermissionFlags(skipPermissions: true, sandboxEnabled: true) == ["--yolo"])
    }

    @Test("Claude stream JSON prefers result text and captures session id")
    func claudeResultAndSessionID() {
        let stdout = """
        {"type":"system","subtype":"init","session_id":"claude-session-1"}
        {"type":"assistant","session_id":"claude-session-1","message":{"content":[{"type":"text","text":"draft"}]}}
        {"type":"result","session_id":"claude-session-1","result":"final answer"}
        """

        let parsed = AgentChatRuntime.parseClaudeStreamJSON(stdout)
        #expect(parsed.conversationSessionID == "claude-session-1")
        #expect(parsed.assistantText == "final answer")
    }

    @Test("Claude stream JSON falls back to assistant message blocks")
    func claudeAssistantMessageFallback() {
        let stdout = """
        {"type":"assistant","session_id":"claude-session-2","message":{"content":[{"type":"text","text":"hello from assistant"}]}}
        """

        let parsed = AgentChatRuntime.parseClaudeStreamJSON(stdout)
        #expect(parsed.conversationSessionID == "claude-session-2")
        #expect(parsed.assistantText == "hello from assistant")
    }

    @Test("Codex JSONL extracts thread id and assistant text")
    func codexThreadAndAssistantMessage() {
        let stdout = """
        {"type":"thread.started","thread_id":"codex-thread-1"}
        {"type":"turn.started"}
        {"type":"item.completed","item":{"id":"item_0","type":"agent_message","text":"codex reply"}}
        {"type":"turn.completed"}
        """

        let parsed = AgentChatRuntime.parseCodexJSONL(stdout)
        #expect(parsed.conversationSessionID == "codex-thread-1")
        #expect(parsed.assistantText == "codex reply")
    }

    @Test("Codex transcript reconciliation preserves commentary and tool calls")
    func codexTranscriptReconciliationPreservesCodexEvents() {
        let existingUser = PersistedChatMessage(
            role: .user,
            text: "hello",
            attachments: [PersistedChatAttachment(filePath: "/tmp/a.png", kind: .image)],
            modelId: "gpt-5.5",
            reasoningLevel: "low"
        )
        let jsonl = """
        {"timestamp":"2026-05-22T08:00:00Z","type":"event_msg","payload":{"type":"user_message","message":"hello"}}
        {"timestamp":"2026-05-22T08:00:01Z","type":"event_msg","payload":{"type":"agent_message","message":"I’ll inspect first.","phase":"commentary"}}
        {"timestamp":"2026-05-22T08:00:02Z","type":"response_item","payload":{"type":"function_call","name":"exec_command","arguments":"{\\"cmd\\":\\"rg hello\\"}","call_id":"call_1"}}
        {"timestamp":"2026-05-22T08:00:03Z","type":"response_item","payload":{"type":"function_call_output","call_id":"call_1","output":"found"}}
        {"timestamp":"2026-05-22T08:00:04Z","type":"event_msg","payload":{"type":"agent_message","message":"Done.","phase":"final_answer"}}
        {"timestamp":"2026-05-22T08:00:05Z","type":"event_msg","payload":{"type":"task_complete"}}
        """

        let messages = CodexChatTranscriptReconciler.messages(
            fromCodexJSONL: jsonl,
            existingMessages: [existingUser]
        )

        #expect(messages.map(\.role) == [.user, .assistant, .assistant, .assistant])
        #expect(messages[0].attachments == existingUser.attachments)
        #expect(messages[0].modelId == "gpt-5.5")
        #expect(messages[0].reasoningLevel == "low")
        #expect(messages[1].text == "I’ll inspect first.")
        #expect(messages[2].text.contains("Tool result: exec_command"))
        #expect(messages[2].text.contains("rg hello"))
        #expect(messages[2].text.contains("Output:\nfound"))
        #expect(messages[3].text == "Done.")
    }


    @Test("Tool transcript formatter parses JSON and summarizes folded headers")
    func toolTranscriptFormatterParsesJSONAndSummarizesHeaders() {
        let presentation = ChatToolTranscriptFormatter.presentation(
            for: ChatToolTranscriptFormatter.toolCallText(
                name: "exec_command",
                arguments: "{\"cmd\":\"rg hello\",\"yield_time_ms\":1000}"
            )
        )

        #expect(presentation?.kind == .call)
        #expect(presentation?.title == "rg hello")
        #expect(presentation?.detail == "exec_command")
        #expect(presentation?.body.contains("Command\nrg hello") == true)
        #expect(presentation?.body.contains("Yield time: 1000 ms") == true)
    }

    @Test("Tool transcript formatter summarizes command output envelopes")
    func toolTranscriptFormatterSummarizesCommandOutputEnvelopes() {
        let presentation = ChatToolTranscriptFormatter.presentation(
            for: ChatToolTranscriptFormatter.toolOutputText(
                """
                Chunk ID: abc123
                Wall time: 0.0801 seconds
                Process exited with code 0
                Original token count: 42
                Output:
                {"changed":true,"files":["A.swift","B.swift"]}
                """
            )
        )

        #expect(presentation?.kind == .output)
        #expect(presentation?.title == "Changed: true · Files: A.swift, B.swift")
        #expect(presentation?.detail == nil)
        #expect(presentation?.body.contains("Status\nExit code: 0") == false)
        #expect(presentation?.body.contains("Tokens: 42") == false)
        #expect(presentation?.body.contains("Changed: true") == true)
        #expect(presentation?.body.contains("Files: A.swift, B.swift") == true)
    }

    @Test("Tool transcript formatter labels paired tool output")
    func toolTranscriptFormatterLabelsPairedToolOutput() {
        let presentation = ChatToolTranscriptFormatter.presentation(
            for: ChatToolTranscriptFormatter.toolOutputText("found", name: "exec_command")
        )

        #expect(presentation?.kind == .output)
        #expect(presentation?.title == "exec_command")
        #expect(presentation?.detail == "for exec_command")
        #expect(presentation?.body.contains("Output\nfound") == true)
    }

    @Test("Codex chat tab restore skips tabs without session ids")
    func codexChatTabRestoreSkipsTabsWithoutSessionIDs() {
        let tab = PersistedChatTab(
            identifier: "chat:1",
            agentType: .codex,
            title: "Codex",
            messages: [PersistedChatMessage(role: .assistant, text: "Done.")]
        )

        let result = CodexChatTranscriptReconciler.reconciledChatTabsForRestore([tab])

        #expect(!result.didMutate)
        #expect(result.chatTabs == [tab])
    }

    @Test("Codex transcript reconciliation restores incomplete turns as loading")
    func codexTranscriptReconciliationRestoresIncompleteTurnAsLoading() {
        let jsonl = """
        {"timestamp":"2026-05-22T08:00:00Z","type":"event_msg","payload":{"type":"user_message","message":"keep working"}}
        {"timestamp":"2026-05-22T08:00:01Z","type":"event_msg","payload":{"type":"agent_message","message":"I’ll start.","phase":"commentary"}}
        """

        let messages = CodexChatTranscriptReconciler.messages(fromCodexJSONL: jsonl)

        #expect(messages.map(\.role) == [.user, .assistant, .assistant])
        #expect(messages[2].text == "Thinking...")
        #expect(messages[2].createdAt == messages[0].createdAt)
    }

    @Test("Codex transcript reconciliation does not restore loading for completed turns")
    func codexTranscriptReconciliationDoesNotRestoreLoadingForCompletedTurn() {
        let jsonl = """
        {"timestamp":"2026-05-22T08:00:00Z","type":"event_msg","payload":{"type":"user_message","message":"finish"}}
        {"timestamp":"2026-05-22T08:00:01Z","type":"event_msg","payload":{"type":"agent_message","message":"Done.","phase":"final_answer"}}
        {"timestamp":"2026-05-22T08:00:02Z","type":"event_msg","payload":{"type":"task_complete"}}
        """

        let messages = CodexChatTranscriptReconciler.messages(fromCodexJSONL: jsonl)

        #expect(messages.map(\.role) == [.user, .assistant])
        #expect(messages.last?.text == "Done.")
    }

    @Test("Codex transcript reconciliation preserves existing attachments across attachment footer")
    func codexTranscriptReconciliationPreservesAttachmentsAcrossAttachmentFooter() throws {
        let directory = URL(fileURLWithPath: NSTemporaryDirectory())
            .appendingPathComponent("magent-codex-attachment-\(UUID().uuidString)", isDirectory: true)
        try FileManager.default.createDirectory(at: directory, withIntermediateDirectories: true)
        let imageURL = directory.appendingPathComponent("Screenshot.png")
        try Data([0x89, 0x50, 0x4E, 0x47]).write(to: imageURL)
        defer { try? FileManager.default.removeItem(at: directory) }

        let existingUser = PersistedChatMessage(
            role: .user,
            text: "can you read whats on this image?",
            attachments: [PersistedChatAttachment(filePath: imageURL.path, kind: .image)]
        )
        let jsonl = """
        {"timestamp":"2026-05-22T08:00:00Z","type":"event_msg","payload":{"type":"user_message","message":"can you read whats on this image?\\n\\nAttached files:\\n- file://\(imageURL.path) (image, local path: \(imageURL.path))","local_images":["\(imageURL.path)"]}}
        {"timestamp":"2026-05-22T08:00:01Z","type":"event_msg","payload":{"type":"agent_message","message":"It says Uncommitted."}}
        {"timestamp":"2026-05-22T08:00:02Z","type":"event_msg","payload":{"type":"task_complete"}}
        """

        let messages = CodexChatTranscriptReconciler.messages(
            fromCodexJSONL: jsonl,
            existingMessages: [existingUser]
        )

        #expect(messages.first?.id == existingUser.id)
        #expect(messages.first?.text == "can you read whats on this image?")
        #expect(messages.first?.attachments == existingUser.attachments)
    }

    @Test("Codex transcript reconciliation ignores near-duplicate user replay")
    func codexTranscriptReconciliationIgnoresNearDuplicateUserReplay() {
        let jsonl = """
        {"timestamp":"2026-05-22T08:00:00Z","type":"event_msg","payload":{"type":"user_message","message":"repeat me"}}
        {"timestamp":"2026-05-22T08:00:01Z","type":"event_msg","payload":{"type":"agent_message","message":"First"}}
        {"timestamp":"2026-05-22T08:04:00Z","type":"event_msg","payload":{"type":"user_message","message":"repeat me"}}
        {"timestamp":"2026-05-22T08:04:01Z","type":"event_msg","payload":{"type":"agent_message","message":"Second"}}
        {"timestamp":"2026-05-22T08:04:02Z","type":"event_msg","payload":{"type":"task_complete"}}
        """

        let messages = CodexChatTranscriptReconciler.messages(fromCodexJSONL: jsonl)

        #expect(messages.filter { $0.role == .user }.map(\.text) == ["repeat me"])
        #expect(messages.filter { $0.role == .assistant }.map(\.text) == ["First"])
    }

    @Test("Claude transcript reconciliation preserves user, assistant, and tool events")
    func claudeTranscriptReconciliationPreservesClaudeEvents() {
        let existingUser = PersistedChatMessage(
            role: .user,
            text: "inspect this",
            attachments: [PersistedChatAttachment(filePath: "/tmp/b.png", kind: .image)],
            modelId: "claude-opus-4-6"
        )
        let jsonl = """
        {"type":"user","timestamp":"2026-05-22T08:00:00Z","message":{"role":"user","content":[{"type":"text","text":"inspect this"}]}}
        {"type":"assistant","timestamp":"2026-05-22T08:00:01Z","message":{"role":"assistant","content":[{"type":"tool_use","id":"toolu_1","name":"Read","input":{"file_path":"/tmp/file.swift"}}],"stop_reason":"tool_use"}}
        {"type":"user","timestamp":"2026-05-22T08:00:02Z","message":{"role":"user","content":[{"type":"tool_result","tool_use_id":"toolu_1","content":"file contents"}]}}
        {"type":"assistant","timestamp":"2026-05-22T08:00:03Z","message":{"role":"assistant","content":[{"type":"text","text":"Done."}],"stop_reason":"end_turn"}}
        """

        let messages = ClaudeChatTranscriptReconciler.messages(
            fromClaudeJSONL: jsonl,
            existingMessages: [existingUser]
        )

        #expect(messages.map(\.role) == [.user, .assistant, .assistant])
        #expect(messages[0].attachments == existingUser.attachments)
        #expect(messages[0].modelId == "claude-opus-4-6")
        #expect(messages[1].text.contains("Tool result: Read"))
        #expect(messages[1].text.contains("file_path"))
        #expect(messages[1].text.contains("Output:\nfile contents"))
        #expect(messages[2].text == "Done.")
    }

    @Test("Claude chat tab restore skips tabs without session ids")
    func claudeChatTabRestoreSkipsTabsWithoutSessionIDs() {
        let tab = PersistedChatTab(
            identifier: "chat:1",
            agentType: .claude,
            title: "Claude",
            messages: [PersistedChatMessage(role: .assistant, text: "Done.")]
        )

        let result = ClaudeChatTranscriptReconciler.reconciledChatTabsForRestore([tab])

        #expect(!result.didMutate)
        #expect(result.chatTabs == [tab])
    }

    @Test("Claude transcript reconciliation restores incomplete turns as loading")
    func claudeTranscriptReconciliationRestoresIncompleteTurnAsLoading() {
        let jsonl = """
        {"type":"user","timestamp":"2026-05-22T08:00:00Z","message":{"role":"user","content":[{"type":"text","text":"keep working"}]}}
        {"type":"assistant","timestamp":"2026-05-22T08:00:01Z","message":{"role":"assistant","content":[{"type":"tool_use","name":"Read","input":{"file_path":"/tmp/file.swift"}}],"stop_reason":"tool_use"}}
        """

        let messages = ClaudeChatTranscriptReconciler.messages(fromClaudeJSONL: jsonl)

        #expect(messages.map(\.role) == [.user, .assistant, .assistant])
        #expect(messages[2].text == "Thinking...")
        #expect(messages[2].createdAt == messages[0].createdAt)
    }

    @Test("Claude model-change text parsing returns model label and effort")
    func claudeModelChangeParsing() {
        let output = """
        Some other text
        ⎿ Set model to Opus 4.1 with high effort
        """

        let parsed = AgentChatRuntime.parseClaudeModelChange(from: output)
        #expect(parsed?.modelLabel == "Opus 4.1")
        #expect(parsed?.effortLevel == "high")
    }

    @Test("Codex model-change text parsing returns model id and effort")
    func codexModelChangeParsing() {
        let output = """
        note
        • Model changed to gpt-5.5 xhigh
        """

        let parsed = AgentChatRuntime.parseCodexModelChange(from: output)
        #expect(parsed?.modelId == "gpt-5.5")
        #expect(parsed?.effortLevel == "xhigh")
    }
}

// MARK: - IPCRequest

@Suite("IPCRequest decoding")
struct IPCRequestDecodingTests {

    @Test("Decodes create-web-tab payload with url and title")
    func decodesCreateWebTab() throws {
        let json = """
        {"command":"create-web-tab","threadName":"kimchi","url":"https://example.com/docs","title":"Docs"}
        """.data(using: .utf8)!
        let request = try JSONDecoder().decode(IPCRequest.self, from: json)
        #expect(request.command == "create-web-tab")
        #expect(request.threadName == "kimchi")
        #expect(request.url == "https://example.com/docs")
        #expect(request.title == "Docs")
    }

    @Test("url field is optional and absent on unrelated commands")
    func urlOptional() throws {
        let json = """
        {"command":"list-threads"}
        """.data(using: .utf8)!
        let request = try JSONDecoder().decode(IPCRequest.self, from: json)
        #expect(request.url == nil)
    }

    @Test("Decodes newName field for tab naming commands")
    func decodesNewName() throws {
        let json = """
        {"command":"create-tab","threadName":"kimchi","newName":"Review"}
        """.data(using: .utf8)!
        let request = try JSONDecoder().decode(IPCRequest.self, from: json)
        #expect(request.command == "create-tab")
        #expect(request.newName == "Review")
    }
}

// MARK: - PersistedWebTab

@Suite("PersistedWebTab display title")
struct PersistedWebTabDisplayTitleTests {

    @Test("Uses customTitle when present")
    func usesCustomTitle() throws {
        let url = try #require(URL(string: "https://example.com/docs"))
        let tab = PersistedWebTab(
            identifier: "web:test",
            url: url,
            title: "example.com",
            iconType: .web,
            customTitle: "Docs"
        )
        #expect(tab.displayTitle == "Docs")
    }

    @Test("Falls back to title when customTitle is nil")
    func fallsBackToTitle() throws {
        let url = try #require(URL(string: "https://example.com/docs"))
        let tab = PersistedWebTab(
            identifier: "web:test",
            url: url,
            title: "example.com",
            iconType: .web,
            customTitle: nil
        )
        #expect(tab.displayTitle == "example.com")
    }
}

// MARK: - IPCTabInfo

@Suite("IPCTabInfo")
struct IPCTabInfoTests {

    @Test("Carries optional tabType and keeps default nil")
    func tabTypeInitBehavior() {
        let terminal = IPCTabInfo(index: 0, sessionName: "ma-repo-thread", isAgent: true, tabType: "terminal")
        #expect(terminal.tabType == "terminal")
        #expect(terminal.isPinned == nil)

        let legacy = IPCTabInfo(index: 1, sessionName: "ma-repo-thread-2", isAgent: false)
        #expect(legacy.tabType == nil)
        #expect(legacy.isPinned == nil)
    }
}

// MARK: - ExternalLinkOpenRouting

@Suite("ExternalLinkOpenRouting")
struct ExternalLinkOpenRoutingTests {

    @Test("Prefers popped-out thread windows over main-window routes")
    func prefersPoppedOutThread() {
        let route = ExternalLinkOpenRouting.resolve(
            isThreadPoppedOut: true,
            isCurrentMainThread: true
        )
        #expect(route == .poppedOutThreadWindow)
    }

    @Test("Uses current main thread when the target thread is already visible")
    func currentMainThreadRoute() {
        let route = ExternalLinkOpenRouting.resolve(
            isThreadPoppedOut: false,
            isCurrentMainThread: true
        )
        #expect(route == .currentMainThread)
    }

    @Test("Selects the thread in the main window when not currently visible")
    func selectMainThreadRoute() {
        let route = ExternalLinkOpenRouting.resolve(
            isThreadPoppedOut: false,
            isCurrentMainThread: false
        )
        #expect(route == .selectThreadInMainWindow)
    }
}

// MARK: - ThreadTabStructureFingerprint

@Suite("ThreadTabStructureFingerprint")
struct ThreadTabStructureFingerprintTests {

    @Test("Ignores transient thread status fields")
    func ignoresTransientStatus() throws {
        let base = makeThread(
            tmuxSessions: ["ma-repo-thread-claude"],
            pinnedSessions: ["ma-repo-thread-claude"]
        )
        var updated = base
        updated.isDirty = true
        updated.isFullyDelivered = true
        updated.busySessions.insert("ma-repo-thread-claude")
        updated.waitingForInputSessions.insert("ma-repo-thread-claude")
        updated.unreadCompletionSessions.insert("ma-repo-thread-claude")

        #expect(ThreadTabStructureFingerprint(thread: base) == ThreadTabStructureFingerprint(thread: updated))
    }

    @Test("Changes when terminal sessions change")
    func changesOnTerminalSessions() throws {
        let base = makeThread(tmuxSessions: ["ma-repo-thread-claude"])
        let updated = makeThread(tmuxSessions: ["ma-repo-thread-claude", "ma-repo-thread-codex"])

        #expect(ThreadTabStructureFingerprint(thread: base) != ThreadTabStructureFingerprint(thread: updated))
    }

    @Test("Changes when web tabs or their pinning change")
    func changesOnWebTabs() throws {
        let webURL = try #require(URL(string: "https://example.com/docs"))
        let base = makeThread(
            webTabs: [
                PersistedWebTab(
                    identifier: "web:docs",
                    url: webURL,
                    title: "Docs",
                    iconType: .web,
                    isPinned: false
                ),
            ]
        )
        let updated = makeThread(
            webTabs: [
                PersistedWebTab(
                    identifier: "web:docs",
                    url: webURL,
                    title: "Docs",
                    iconType: .web,
                    isPinned: true
                ),
            ]
        )

        #expect(ThreadTabStructureFingerprint(thread: base) != ThreadTabStructureFingerprint(thread: updated))
    }

    @Test("Changes when draft tab identifiers change")
    func changesOnDraftTabs() {
        let base = makeThread(
            draftTabs: [
                PersistedDraftTab(identifier: "draft:1", agentType: .codex, prompt: "A"),
            ]
        )
        let updated = makeThread(
            draftTabs: [
                PersistedDraftTab(identifier: "draft:2", agentType: .codex, prompt: "A"),
            ]
        )

        #expect(ThreadTabStructureFingerprint(thread: base) != ThreadTabStructureFingerprint(thread: updated))
    }

    @Test("Changes when draft tab pinning changes")
    func changesOnDraftTabPinning() {
        let base = makeThread(
            draftTabs: [
                PersistedDraftTab(identifier: "draft:1", agentType: .codex, prompt: "A", isPinned: false),
            ]
        )
        let updated = makeThread(
            draftTabs: [
                PersistedDraftTab(identifier: "draft:1", agentType: .codex, prompt: "A", isPinned: true),
            ]
        )

        #expect(ThreadTabStructureFingerprint(thread: base) != ThreadTabStructureFingerprint(thread: updated))
    }

    @Test("Changes when chat tab pinning changes")
    func changesOnChatTabPinning() {
        let base = makeThread(
            chatTabs: [
                PersistedChatTab(identifier: "chat:1", agentType: .codex, title: "Chat", isPinned: false),
            ]
        )
        let updated = makeThread(
            chatTabs: [
                PersistedChatTab(identifier: "chat:1", agentType: .codex, title: "Chat", isPinned: true),
            ]
        )

        #expect(ThreadTabStructureFingerprint(thread: base) != ThreadTabStructureFingerprint(thread: updated))
    }

    private func makeThread(
        tmuxSessions: [String] = [],
        pinnedSessions: [String] = [],
        webTabs: [PersistedWebTab] = [],
        draftTabs: [PersistedDraftTab] = [],
        chatTabs: [PersistedChatTab] = []
    ) -> MagentThread {
        MagentThread(
            projectId: UUID(),
            name: "thread",
            worktreePath: "/tmp/thread",
            branchName: "thread",
            tmuxSessionNames: tmuxSessions,
            pinnedTmuxSessions: pinnedSessions,
            persistedWebTabs: webTabs,
            persistedDraftTabs: draftTabs,
            persistedChatTabs: chatTabs
        )
    }
}

@Suite("MagentThread diff state persistence")
struct MagentThreadDiffStatePersistenceTests {

    @Test("Persists diff collapsed file state through Codable")
    func persistsDiffCollapsedFileStateThroughCodable() throws {
        let original = MagentThread(
            projectId: UUID(),
            name: "thread",
            worktreePath: "/tmp/thread",
            branchName: "thread",
            diffReviewedFileSignatures: [
                "Sources/App.swift": "code-v2\nstatus:modified\nadd:1:hello",
            ],
            diffCollapsedFileStates: [
                "Sources/App.swift": true,
                "Tests/AppTests.swift": false,
            ]
        )

        let data = try JSONEncoder().encode(original)
        let decoded = try JSONDecoder().decode(MagentThread.self, from: data)

        #expect(decoded.diffReviewedFileSignatures == original.diffReviewedFileSignatures)
        #expect(decoded.diffCollapsedFileStates == original.diffCollapsedFileStates)
    }
}

@Suite("MagentThread favorite alias persistence")
struct MagentThreadFavoriteAliasPersistenceTests {

    @Test("Persists favorite alias independently from favorite membership")
    func persistsFavoriteAliasIndependentlyFromFavoriteMembership() throws {
        let original = MagentThread(
            projectId: UUID(),
            name: "thread",
            worktreePath: "/tmp/thread",
            branchName: "thread",
            isFavorite: false,
            favoritedAt: nil,
            favoriteAlias: "Short status name"
        )

        let data = try JSONEncoder().encode(original)
        let decoded = try JSONDecoder().decode(MagentThread.self, from: data)

        #expect(!decoded.isFavorite)
        #expect(decoded.favoritedAt == nil)
        #expect(decoded.favoriteAlias == "Short status name")
    }
}

@Suite("MagentThread completion identifiers")
struct MagentThreadCompletionIdentifierTests {

    @Test("Includes terminal sessions and chat tabs")
    func includesTerminalAndChatIdentifiers() {
        let thread = MagentThread(
            projectId: UUID(),
            name: "thread",
            worktreePath: "/tmp/thread",
            branchName: "thread",
            tmuxSessionNames: ["ma-repo-thread-claude"],
            persistedChatTabs: [
                PersistedChatTab(identifier: "chat:1", agentType: .codex, title: "Chat"),
                PersistedChatTab(identifier: "chat:2", agentType: .claude, title: "Chat 2"),
            ]
        )

        #expect(thread.completionTrackedTabIdentifiers == Set(["ma-repo-thread-claude", "chat:1", "chat:2"]))
    }

    @Test("Excludes web and draft identifiers")
    func excludesWebAndDraftIdentifiers() throws {
        let url = try #require(URL(string: "https://example.com"))
        let thread = MagentThread(
            projectId: UUID(),
            name: "thread",
            worktreePath: "/tmp/thread",
            branchName: "thread",
            tmuxSessionNames: [],
            persistedWebTabs: [
                PersistedWebTab(identifier: "web:1", url: url, title: "Example", iconType: .web),
            ],
            persistedDraftTabs: [
                PersistedDraftTab(identifier: "draft:1", agentType: .codex, prompt: "Prompt"),
            ],
            persistedChatTabs: [
                PersistedChatTab(identifier: "chat:1", agentType: .codex, title: "Chat"),
            ]
        )

        #expect(thread.completionTrackedTabIdentifiers == Set(["chat:1"]))
    }
}

// MARK: - CreatedTerminalTabReconciler

@Suite("CreatedTerminalTabReconciler")
struct CreatedTerminalTabReconcilerTests {

    @Test("Prefers an existing created session over pending placeholder")
    func prefersExistingSession() {
        let placement = CreatedTerminalTabReconciler.resolvePlacement(
            createdSessionName: "ma-repo-thread-codex",
            displaySlots: ["ma-repo-thread-claude", "", "ma-repo-thread-codex"],
            pendingIndex: 1
        )

        #expect(placement == .alreadyPresent(index: 2))
    }

    @Test("Replaces pending placeholder when created session is not yet in display slots")
    func replacesPendingPlaceholder() {
        let placement = CreatedTerminalTabReconciler.resolvePlacement(
            createdSessionName: "ma-repo-thread-codex",
            displaySlots: ["ma-repo-thread-claude", ""],
            pendingIndex: 1
        )

        #expect(placement == .replacePending(index: 1))
    }

    @Test("Appends when pending index is no longer valid")
    func appendsWhenPendingIndexInvalid() {
        let placement = CreatedTerminalTabReconciler.resolvePlacement(
            createdSessionName: "ma-repo-thread-codex",
            displaySlots: ["ma-repo-thread-claude", "ma-repo-thread-web"],
            pendingIndex: 5
        )

        #expect(placement == .append)
    }

    @Test("Appends when pending slot is a non-terminal tab")
    func appendsWhenPendingSlotIsNonTerminal() {
        let placement = CreatedTerminalTabReconciler.resolvePlacement(
            createdSessionName: "ma-repo-thread-codex",
            displaySlots: ["ma-repo-thread-claude", nil],
            pendingIndex: 1
        )

        #expect(placement == .append)
    }
}

// MARK: - NewTabSelectionResolver

@Suite("NewTabSelectionResolver")
struct NewTabSelectionResolverTests {

    @Test("Keeps current selection when switch-to-new-tab is disabled")
    func keepsCurrentSelectionWhenSwitchDisabled() {
        let selected = NewTabSelectionResolver.resolveLastSelectedIdentifier(
            currentIdentifier: "ma-repo-thread-old",
            createdSessionIdentifier: "ma-repo-thread-new",
            shouldSwitchToCreatedTab: false
        )

        #expect(selected == "ma-repo-thread-old")
    }

    @Test("Selects created tab when switch-to-new-tab is enabled")
    func selectsCreatedTabWhenSwitchEnabled() {
        let selected = NewTabSelectionResolver.resolveLastSelectedIdentifier(
            currentIdentifier: "ma-repo-thread-old",
            createdSessionIdentifier: "ma-repo-thread-new",
            shouldSwitchToCreatedTab: true
        )

        #expect(selected == "ma-repo-thread-new")
    }

    @Test("Ignores blank created session names and keeps current selection")
    func ignoresBlankCreatedSessionName() {
        let selected = NewTabSelectionResolver.resolveLastSelectedIdentifier(
            currentIdentifier: "ma-repo-thread-old",
            createdSessionIdentifier: "   ",
            shouldSwitchToCreatedTab: true
        )

        #expect(selected == "ma-repo-thread-old")
    }
}

// MARK: - TabRestoreSelectionResolver

@Suite("TabRestoreSelectionResolver")
struct TabRestoreSelectionResolverTests {

    @Test("Prefers magent-busy last-selected tab over stale defaults")
    func prefersBusyLastSelectedOverDefaults() {
        let threadId = UUID()
        let oldSession = "ma-repo-thread-old"
        let newSession = "ma-repo-thread-new"
        let index = TabRestoreSelectionResolver.resolveInitialTerminalIndex(
            orderedSessions: [oldSession, newSession],
            threadId: threadId,
            defaultsThreadId: threadId,
            defaultsIdentifier: oldSession,
            lastSelectedIdentifier: newSession,
            magentBusySessions: [newSession]
        )

        #expect(index == 1)
    }

    @Test("Uses defaults when last-selected tab is not magent-busy")
    func usesDefaultsWhenLastSelectedNotBusy() {
        let threadId = UUID()
        let oldSession = "ma-repo-thread-old"
        let newSession = "ma-repo-thread-new"
        let index = TabRestoreSelectionResolver.resolveInitialTerminalIndex(
            orderedSessions: [oldSession, newSession],
            threadId: threadId,
            defaultsThreadId: threadId,
            defaultsIdentifier: oldSession,
            lastSelectedIdentifier: newSession,
            magentBusySessions: []
        )

        #expect(index == 0)
    }

    @Test("Falls back to last-selected when defaults are for another thread")
    func fallsBackToLastSelectedWhenDefaultsThreadDiffers() {
        let threadId = UUID()
        let index = TabRestoreSelectionResolver.resolveInitialTerminalIndex(
            orderedSessions: ["ma-repo-thread-1", "ma-repo-thread-2"],
            threadId: threadId,
            defaultsThreadId: UUID(),
            defaultsIdentifier: "ma-repo-thread-1",
            lastSelectedIdentifier: "ma-repo-thread-2",
            magentBusySessions: []
        )

        #expect(index == 1)
    }
}

// MARK: - TabStructureRebuildGate

@Suite("TabStructureRebuildGate")
struct TabStructureRebuildGateTests {

    @Test("Allows setupTabs rebuild when no local auto-switch creation is running")
    func allowsRebuildWhenNoLocalCreation() {
        #expect(
            TabStructureRebuildGate.shouldRunSetupTabsAfterStructureChange(
                localAutoSwitchTabCreationsInFlight: 0
            )
        )
    }

    @Test("Suppresses setupTabs rebuild while local auto-switch creation is in flight")
    func suppressesRebuildWhenLocalCreationInFlight() {
        #expect(
            !TabStructureRebuildGate.shouldRunSetupTabsAfterStructureChange(
                localAutoSwitchTabCreationsInFlight: 1
            )
        )
    }
}

// MARK: - RateLimitCacheEntry

@Suite("RateLimitCacheEntry")
struct RateLimitCacheEntryTests {

    @Test("Sets detectedAt for a newly created fingerprint")
    func setsDetectedAtForNewFingerprint() {
        let now = Date(timeIntervalSince1970: 1_700_000_000)
        let entry = RateLimitCacheEntry.preservingFirstDetectedAt(
            resetAt: now.addingTimeInterval(3_600),
            anchorSession: "ma-thread-a",
            anchorPrompt: "prompt a",
            now: now
        )

        #expect(entry.detectedAt == now)
    }

    @Test("Preserves detectedAt across subsequent detections for the same fingerprint")
    func preservesDetectedAtForExistingFingerprint() {
        let firstSeen = Date(timeIntervalSince1970: 1_700_000_000)
        let laterSeen = firstSeen.addingTimeInterval(600)

        let initial = RateLimitCacheEntry.preservingFirstDetectedAt(
            resetAt: firstSeen.addingTimeInterval(1_800),
            anchorSession: "ma-thread-a",
            anchorPrompt: "prompt a",
            now: firstSeen
        )

        let updated = RateLimitCacheEntry.preservingFirstDetectedAt(
            resetAt: laterSeen.addingTimeInterval(3_600),
            anchorSession: "ma-thread-b",
            anchorPrompt: "prompt b",
            now: laterSeen,
            existingEntry: initial
        )

        #expect(updated.detectedAt == firstSeen)
    }

    @Test("Reactivation clears stale tombstone metadata")
    func reactivationClearsStaleMetadata() {
        let firstSeen = Date(timeIntervalSince1970: 1_700_000_000)
        let staleAt = firstSeen.addingTimeInterval(1_200)
        let laterSeen = firstSeen.addingTimeInterval(2_400)

        let staleEntry = RateLimitCacheEntry(
            resetAt: firstSeen.addingTimeInterval(1_800),
            anchorSession: "ma-thread-a",
            anchorPrompt: "prompt a",
            detectedAt: firstSeen,
            staleAt: staleAt,
            staleReason: "prompt_changed"
        )

        let reactivated = RateLimitCacheEntry.preservingFirstDetectedAt(
            resetAt: laterSeen.addingTimeInterval(3_600),
            anchorSession: "ma-thread-a",
            anchorPrompt: "prompt b",
            now: laterSeen,
            existingEntry: staleEntry
        )

        #expect(reactivated.detectedAt == firstSeen)
        #expect(reactivated.staleAt == nil)
        #expect(reactivated.staleReason == nil)
    }

    @Test("Decodes legacy cache entries without detectedAt")
    func decodesLegacyEntriesWithoutDetectedAt() throws {
        let data = Data(
            #"{"fp":{"resetAt":"2026-04-27T12:00:00Z","anchorSession":"ma-thread-a","anchorPrompt":"prompt a"}}"#
                .utf8
        )
        let decoder = JSONDecoder()
        decoder.dateDecodingStrategy = .iso8601

        let decoded = try decoder.decode([String: RateLimitCacheEntry].self, from: data)
        let entry = try #require(decoded["fp"])
        #expect(entry.detectedAt == nil)
        #expect(entry.staleAt == nil)
        #expect(entry.staleReason == nil)
    }
}

// MARK: - RateLimitFingerprinting

@Suite("RateLimitFingerprinting")
struct RateLimitFingerprintingTests {

    @Test("Relative reset fingerprints do not drift as now advances")
    func relativeResetFingerprintsDoNotDrift() {
        let focusText = "You've hit your limit. Try again in 5 hours.\n1. Stop and wait for limit to reset"
        let firstReset = Date(timeIntervalSince1970: 1_800_000_000)
        let laterReset = firstReset.addingTimeInterval(65)

        let first = RateLimitFingerprinting.structuredFingerprint(
            resetAt: firstReset,
            agent: .claude,
            detectorMode: "claude_prompt_menu",
            focusText: focusText,
            hasRelativeReset: true
        )
        let later = RateLimitFingerprinting.structuredFingerprint(
            resetAt: laterReset,
            agent: .claude,
            detectorMode: "claude_prompt_menu",
            focusText: focusText,
            hasRelativeReset: true
        )

        #expect(first == later)
        #expect(first.contains("|relative|"))
    }

    @Test("Absolute reset fingerprints stay keyed by reset minute")
    func absoluteResetFingerprintsUseResetMinute() {
        let focusText = "You've hit your limit · resets 4pm (Europe/Warsaw)"
        let firstReset = Date(timeIntervalSince1970: 1_800_000_000)
        let laterReset = firstReset.addingTimeInterval(60)

        let first = RateLimitFingerprinting.structuredFingerprint(
            resetAt: firstReset,
            agent: .claude,
            detectorMode: "claude_prompt_menu",
            focusText: focusText,
            hasRelativeReset: false
        )
        let later = RateLimitFingerprinting.structuredFingerprint(
            resetAt: laterReset,
            agent: .claude,
            detectorMode: "claude_prompt_menu",
            focusText: focusText,
            hasRelativeReset: false
        )

        #expect(first != later)
    }
}
