import AppKit
import Foundation
import Testing
import MagentCore

// MARK: - SemanticVersion

@Suite("SemanticVersion parsing")
struct SemanticVersionTests {

    @Test("Parses full x.y.z version")
    func parsesFullVersion() throws {
        let v = try #require(SemanticVersion("1.2.3"))
        #expect(v.major == 1 && v.minor == 2 && v.patch == 3)
    }

    @Test("Accepts leading v/V prefix")
    func parsesLeadingV() throws {
        #expect(SemanticVersion("v1.2.3")?.displayString == "1.2.3")
        #expect(SemanticVersion("V2.0.0")?.displayString == "2.0.0")
    }

    @Test("Defaults missing components to 0")
    func parsesShortForm() throws {
        let major = try #require(SemanticVersion("4"))
        #expect(major.major == 4 && major.minor == 0 && major.patch == 0)

        let majMinor = try #require(SemanticVersion("4.5"))
        #expect(majMinor.minor == 5 && majMinor.patch == 0)
    }

    @Test("Strips pre-release / build suffix after first dash")
    func stripsSuffix() throws {
        let v = try #require(SemanticVersion("1.2.3-alpha.4"))
        #expect(v.major == 1 && v.minor == 2 && v.patch == 3)
    }

    @Test("Trims surrounding whitespace")
    func trimsWhitespace() throws {
        #expect(SemanticVersion("  1.0.0 \n")?.displayString == "1.0.0")
    }

    @Test("Rejects non-numeric components")
    func rejectsNonNumeric() {
        #expect(SemanticVersion("abc") == nil)
        #expect(SemanticVersion("1.x.0") == nil)
        #expect(SemanticVersion("") == nil)
    }

    @Test("Comparable orders major/minor/patch correctly")
    func comparable() throws {
        let a = try #require(SemanticVersion("1.2.3"))
        let b = try #require(SemanticVersion("1.2.4"))
        let c = try #require(SemanticVersion("1.3.0"))
        let d = try #require(SemanticVersion("2.0.0"))
        #expect(a < b)
        #expect(b < c)
        #expect(c < d)
        #expect(!(d < a))
    }
}

// MARK: - NameGenerator

@Suite("NameGenerator.isAutoGenerated")
struct NameGeneratorTests {

    @Test("Recognizes bare pokemon names")
    func bareName() {
        #expect(NameGenerator.isAutoGenerated("pikachu"))
        #expect(NameGenerator.isAutoGenerated("whiscash"))
    }

    @Test("Recognizes pokemon with numeric suffix")
    func numericSuffix() {
        #expect(NameGenerator.isAutoGenerated("pikachu-2"))
        #expect(NameGenerator.isAutoGenerated("eevee-42"))
    }

    @Test("Rejects pokemon with non-numeric suffix")
    func pokemonNonNumeric() {
        #expect(!NameGenerator.isAutoGenerated("pikachu-foo"))
    }

    @Test("Recognizes legacy adjective-noun form")
    func legacyTwoPart() {
        #expect(NameGenerator.isAutoGenerated("swift-falcon"))
        #expect(NameGenerator.isAutoGenerated("bright-brook"))
    }

    @Test("Recognizes legacy adjective-noun-N form")
    func legacyThreePart() {
        #expect(NameGenerator.isAutoGenerated("swift-falcon-7"))
    }

    @Test("Rejects three-part with non-numeric tail")
    func legacyThreePartBad() {
        #expect(!NameGenerator.isAutoGenerated("swift-falcon-foo"))
    }

    @Test("Rejects arbitrary/custom names")
    func customNames() {
        #expect(!NameGenerator.isAutoGenerated("my-feature-branch"))
        #expect(!NameGenerator.isAutoGenerated("fix-bug-in-login"))
        #expect(!NameGenerator.isAutoGenerated("unknownword"))
    }

    @Test("Generate wraps counter modulo pokemonNames count")
    func generateWraps() {
        let count = NameGenerator.pokemonNames.count
        #expect(NameGenerator.generate(counter: 0) == NameGenerator.pokemonNames[0])
        #expect(NameGenerator.generate(counter: count) == NameGenerator.pokemonNames[0])
        #expect(NameGenerator.generate(counter: count + 3) == NameGenerator.pokemonNames[3])
    }
}

// MARK: - shellQuote

@Suite("shellQuote")
struct ShellQuoteTests {

    @Test("Wraps plain strings in single quotes")
    func plain() {
        #expect(shellQuote("hello") == "'hello'")
    }

    @Test("Preserves spaces and special chars")
    func spacesAndSpecials() {
        #expect(shellQuote("a b c") == "'a b c'")
        #expect(shellQuote("$HOME `whoami`") == "'$HOME `whoami`'")
    }

    @Test("Escapes embedded single quotes via close-escape-reopen idiom")
    func embeddedQuote() {
        // "don't" → 'don'\''t'
        #expect(shellQuote("don't") == #"'don'\''t'"#)
    }

    @Test("Handles empty string")
    func empty() {
        #expect(shellQuote("") == "''")
    }
}

// MARK: - TmuxSessionNaming

@Suite("TmuxSessionNaming")
struct TmuxSessionNamingTests {

    @Test("sanitizeForTmux replaces illegal chars with hyphens and lowercases")
    func sanitize() {
        #expect(TmuxSessionNaming.sanitizeForTmux("My Project!") == "my-project-")
        #expect(TmuxSessionNaming.sanitizeForTmux("already_ok-123") == "already_ok-123")
        #expect(TmuxSessionNaming.sanitizeForTmux("a/b:c.d") == "a-b-c-d")
    }

    @Test("repoSlug truncates to 16 chars and trims trailing hyphens")
    func repoSlugTruncation() {
        let long = "thisisaveryverylongproject"
        let slug = TmuxSessionNaming.repoSlug(from: long)
        #expect(slug.count <= 16)
        #expect(slug == "thisisaveryveryl")

        // Trailing hyphens after truncation should be stripped
        let awkward = "short-name-extra-extra"
        let slug2 = TmuxSessionNaming.repoSlug(from: awkward)
        #expect(!slug2.hasSuffix("-"))
    }

    @Test("buildSessionName assembles ma-<repo>-<thread>[-<tab>]")
    func buildSessionName() {
        #expect(TmuxSessionNaming.buildSessionName(repoSlug: "repo", threadName: nil) == "ma-repo")
        #expect(TmuxSessionNaming.buildSessionName(repoSlug: "repo", threadName: "pikachu") == "ma-repo-pikachu")
        #expect(TmuxSessionNaming.buildSessionName(repoSlug: "repo", threadName: "pikachu", tabSlug: "2") == "ma-repo-pikachu-2")
    }

    @Test("isMagentSession accepts ma- and magent- prefixes only")
    func isMagentSession() {
        #expect(TmuxSessionNaming.isMagentSession("ma-repo-thread"))
        #expect(TmuxSessionNaming.isMagentSession("magent-foo"))
        #expect(!TmuxSessionNaming.isMagentSession("mysession"))
        #expect(!TmuxSessionNaming.isMagentSession("map-"))
    }

    @Test("defaultTabDisplayName returns base for each agent type")
    func defaultBase() {
        #expect(TmuxSessionNaming.defaultTabDisplayName(for: .claude) == "Claude")
        #expect(TmuxSessionNaming.defaultTabDisplayName(for: .codex) == "Codex")
        #expect(TmuxSessionNaming.defaultTabDisplayName(for: .custom) == "Custom")
        #expect(TmuxSessionNaming.defaultTabDisplayName(for: nil) == "Terminal")
    }

    @Test("Claude tab name includes model label verbatim")
    func claudeWithModel() {
        let name = TmuxSessionNaming.defaultTabDisplayName(for: .claude, modelLabel: "Sonnet 4.6")
        #expect(name == "Claude (Sonnet 4.6)")
    }

    @Test("Claude tab name includes reasoning level abbreviation")
    func claudeWithEffort() {
        #expect(TmuxSessionNaming.defaultTabDisplayName(for: .claude, reasoningLevel: "high") == "Claude (H)")
        #expect(TmuxSessionNaming.defaultTabDisplayName(for: .claude, reasoningLevel: "medium") == "Claude (M)")
        #expect(TmuxSessionNaming.defaultTabDisplayName(for: .claude, reasoningLevel: "xhigh") == "Claude (xH)")
        #expect(TmuxSessionNaming.defaultTabDisplayName(for: .claude, reasoningLevel: "max") == "Claude (Max)")
    }

    @Test("Claude combines model and effort with comma")
    func claudeCombined() {
        let name = TmuxSessionNaming.defaultTabDisplayName(for: .claude, modelLabel: "Sonnet 4.6", reasoningLevel: "high")
        #expect(name == "Claude (Sonnet 4.6, H)")
    }

    @Test("Codex strips GPT prefix and hyphenates tokens")
    func codexModel() {
        let name = TmuxSessionNaming.defaultTabDisplayName(for: .codex, modelLabel: "GPT 5.3 Codex")
        #expect(name == "Codex (5.3-codex)")
    }

    @Test("Codex collapses multiple spaces and trims")
    func codexCollapse() {
        let name = TmuxSessionNaming.defaultTabDisplayName(for: .codex, modelLabel: "  gpt   5.4-mini  ")
        #expect(name == "Codex (5.4-mini)")
    }

    @Test("Empty/whitespace model label is ignored")
    func emptyModelIgnored() {
        #expect(TmuxSessionNaming.defaultTabDisplayName(for: .claude, modelLabel: "   ") == "Claude")
        #expect(TmuxSessionNaming.defaultTabDisplayName(for: .claude, modelLabel: nil) == "Claude")
    }

    @Test("Custom agent ignores model label")
    func customIgnoresModel() {
        #expect(TmuxSessionNaming.defaultTabDisplayName(for: .custom, modelLabel: "whatever") == "Custom")
    }

    @Test("looksLikeDefaultTabName matches exact base")
    func looksLikeBase() {
        #expect(TmuxSessionNaming.looksLikeDefaultTabName("Claude", for: .claude))
        #expect(TmuxSessionNaming.looksLikeDefaultTabName("Codex", for: .codex))
        #expect(TmuxSessionNaming.looksLikeDefaultTabName("Terminal", for: nil))
    }

    @Test("looksLikeDefaultTabName matches base with valid parenthesised detail")
    func looksLikeWithDetail() {
        #expect(TmuxSessionNaming.looksLikeDefaultTabName("Claude (M)", for: .claude))
        #expect(TmuxSessionNaming.looksLikeDefaultTabName("Claude (Sonnet 4.6)", for: .claude))
        #expect(TmuxSessionNaming.looksLikeDefaultTabName("Claude (Sonnet 4.6, H)", for: .claude))
        #expect(TmuxSessionNaming.looksLikeDefaultTabName("Codex (5.3-codex)", for: .codex))
    }

    @Test("looksLikeDefaultTabName rejects human-meaningful names")
    func looksLikeRejects() {
        #expect(!TmuxSessionNaming.looksLikeDefaultTabName("My Debug Tab", for: .claude))
        #expect(!TmuxSessionNaming.looksLikeDefaultTabName("Claude (my notes!)", for: .claude))
        #expect(!TmuxSessionNaming.looksLikeDefaultTabName("Claude ()", for: .claude))
        // Wrong base
        #expect(!TmuxSessionNaming.looksLikeDefaultTabName("Codex (M)", for: .claude))
    }

    @Test("renamedSessionName rewrites prefix for exact match")
    func renameExact() {
        let renamed = TmuxSessionNaming.renamedSessionName(
            "ma-repo-oldname",
            fromThreadName: "oldname",
            toThreadName: "newname",
            repoSlug: "repo"
        )
        #expect(renamed == "ma-repo-newname")
    }

    @Test("renamedSessionName rewrites prefix while preserving tab suffix")
    func renameWithTab() {
        let renamed = TmuxSessionNaming.renamedSessionName(
            "ma-repo-oldname-tab-2",
            fromThreadName: "oldname",
            toThreadName: "newname",
            repoSlug: "repo"
        )
        #expect(renamed == "ma-repo-newname-tab-2")
    }

    @Test("renamedSessionName leaves unrelated sessions untouched")
    func renameUnrelated() {
        let renamed = TmuxSessionNaming.renamedSessionName(
            "ma-repo-otherthread",
            fromThreadName: "oldname",
            toThreadName: "newname",
            repoSlug: "repo"
        )
        #expect(renamed == "ma-repo-otherthread")
    }

    @Test("renamedSessionName must not match as substring of a longer thread name")
    func renameBoundary() {
        // "ma-repo-oldnameextra" shouldn't be rewritten when renaming "oldname"
        let renamed = TmuxSessionNaming.renamedSessionName(
            "ma-repo-oldnameextra",
            fromThreadName: "oldname",
            toThreadName: "newname",
            repoSlug: "repo"
        )
        #expect(renamed == "ma-repo-oldnameextra")
    }
}

// MARK: - GitRemote parsing

@Suite("GitRemote.parse URL handling")
struct GitRemoteParseTests {

    @Test("Parses SSH shorthand git@host:owner/repo.git")
    func sshShorthand() throws {
        let remote = try #require(GitRemote.parse(name: "origin", rawURL: "git@github.com:owner/repo.git"))
        #expect(remote.host == "github.com")
        #expect(remote.repoPath == "owner/repo")
        #expect(remote.provider == .github)
    }

    @Test("Parses https URLs and strips .git suffix")
    func https() throws {
        let remote = try #require(GitRemote.parse(name: "origin", rawURL: "https://gitlab.com/group/sub/repo.git"))
        #expect(remote.host == "gitlab.com")
        #expect(remote.repoPath == "group/sub/repo")
        #expect(remote.provider == .gitlab)
    }

    @Test("Parses ssh:// URLs with user and port")
    func sshWithPort() throws {
        let remote = try #require(GitRemote.parse(name: "origin", rawURL: "ssh://git@bitbucket.org:7999/team/repo.git"))
        #expect(remote.host == "bitbucket.org")
        #expect(remote.repoPath == "team/repo")
        #expect(remote.provider == .bitbucket)
    }

    @Test("Detects unknown provider for unfamiliar hosts")
    func unknownProvider() throws {
        let remote = try #require(GitRemote.parse(name: "origin", rawURL: "https://git.example.com/owner/repo.git"))
        #expect(remote.provider == .unknown)
    }

    @Test("Returns nil when path is missing")
    func missingPath() {
        #expect(GitRemote.parse(name: "origin", rawURL: "https://github.com") == nil)
        #expect(GitRemote.parse(name: "origin", rawURL: "") == nil)
    }

    @Test("Keeps path when no .git suffix is present")
    func noGitSuffix() throws {
        let remote = try #require(GitRemote.parse(name: "origin", rawURL: "https://github.com/owner/repo"))
        #expect(remote.repoPath == "owner/repo")
    }
}

// MARK: - GitRemote URL builders

@Suite("GitRemote PR URL builders")
struct GitRemotePullRequestURLTests {

    let github = GitRemote.parse(name: "origin", rawURL: "https://github.com/owner/repo.git")!
    let gitlab = GitRemote.parse(name: "origin", rawURL: "https://gitlab.com/group/repo.git")!
    let bitbucket = GitRemote.parse(name: "origin", rawURL: "https://bitbucket.org/team/repo.git")!
    let unknown = GitRemote.parse(name: "origin", rawURL: "https://git.example.com/o/r.git")!

    @Test("Default branch returns open PRs listing")
    func defaultBranchGoesToListing() {
        let url = github.pullRequestURL(for: "main", defaultBranch: "main")
        #expect(url?.absoluteString == "https://github.com/owner/repo/pulls?q=is%3Aopen+is%3Apr")
    }

    @Test("Branch-specific URL for GitHub includes head:<branch> query")
    func githubBranchQuery() {
        let url = github.pullRequestURL(for: "feature x", defaultBranch: "main")
        let encoded = url?.absoluteString ?? ""
        // urlQueryAllowed encodes spaces but not '/', matching GitHub's expected query format.
        #expect(encoded.contains("head%3Afeature%20x"))
    }

    @Test("GitLab uses source_branch query")
    func gitlabBranchQuery() {
        let url = gitlab.pullRequestURL(for: "feature", defaultBranch: "main")
        #expect(url?.absoluteString.contains("source_branch=feature") == true)
        #expect(url?.absoluteString.contains("state=opened") == true)
    }

    @Test("Bitbucket uses source query and state=OPEN")
    func bitbucketBranchQuery() {
        let url = bitbucket.pullRequestURL(for: "feature", defaultBranch: "main")
        #expect(url?.absoluteString.contains("source=feature") == true)
        #expect(url?.absoluteString.contains("state=OPEN") == true)
    }

    @Test("createPullRequestURL requires non-empty source")
    func createPRRequiresSource() {
        #expect(github.createPullRequestURL(sourceBranch: "   ", targetBranch: "main") == nil)
    }

    @Test("GitHub createPullRequestURL requires target and uses compare path")
    func createPRGitHub() throws {
        let url = try #require(github.createPullRequestURL(sourceBranch: "feature", targetBranch: "main", title: "My PR"))
        #expect(url.absoluteString.hasPrefix("https://github.com/owner/repo/compare/main...feature"))
        #expect(url.absoluteString.contains("expand=1"))
        #expect(url.absoluteString.contains("title=My%20PR"))

        #expect(github.createPullRequestURL(sourceBranch: "feature", targetBranch: nil) == nil)
    }

    @Test("GitLab createPullRequestURL builds merge_request form")
    func createPRGitLab() throws {
        let url = try #require(gitlab.createPullRequestURL(sourceBranch: "feature", targetBranch: "main", title: "t"))
        let s = url.absoluteString
        #expect(s.contains("merge_request%5Bsource_branch%5D=feature"))
        #expect(s.contains("merge_request%5Btarget_branch%5D=main"))
        #expect(s.contains("merge_request%5Btitle%5D=t"))
    }

    @Test("Bitbucket createPullRequestURL requires target")
    func createPRBitbucket() throws {
        #expect(bitbucket.createPullRequestURL(sourceBranch: "feature", targetBranch: nil) == nil)
        let url = try #require(bitbucket.createPullRequestURL(sourceBranch: "feature", targetBranch: "main"))
        let s = url.absoluteString
        #expect(s.contains("source=feature"))
        #expect(s.contains("dest=main"))
    }

    @Test("Unknown provider returns nil for createPullRequestURL")
    func createPRUnknown() {
        #expect(unknown.createPullRequestURL(sourceBranch: "feature", targetBranch: "main") == nil)
    }

    @Test("directPullRequestURL varies by provider")
    func directURLs() {
        #expect(github.directPullRequestURL(number: 42)?.absoluteString == "https://github.com/owner/repo/pull/42")
        #expect(gitlab.directPullRequestURL(number: 42)?.absoluteString == "https://gitlab.com/group/repo/-/merge_requests/42")
        #expect(bitbucket.directPullRequestURL(number: 42)?.absoluteString == "https://bitbucket.org/team/repo/pull-requests/42")
        #expect(unknown.directPullRequestURL(number: 42) == nil)
    }
}

// MARK: - BranchUpstreamStatus

@Suite("BranchUpstreamStatus display text")
struct BranchUpstreamStatusTests {

    @Test("Local branch has (local) suffix")
    func localBranch() {
        let s = BranchUpstreamStatus(upstreamRef: nil, aheadCount: nil, behindCount: nil)
        #expect(s.inlineSuffix == "(local)")
        #expect(s.displayText == "Local")
        #expect(s.displayUpstreamRef == nil)
        #expect(s.tooltipText == "This branch has no configured remote counterpart.")
    }

    @Test("Up-to-date returns nil inline suffix")
    func upToDate() {
        let s = BranchUpstreamStatus(upstreamRef: "origin/main", aheadCount: 0, behindCount: 0)
        #expect(s.inlineSuffix == nil)
        #expect(s.displayText == "Up to date with remote")
        #expect(s.tooltipText == "Upstream: main")
    }

    @Test("Ahead-only uses + count")
    func aheadOnly() {
        let s = BranchUpstreamStatus(upstreamRef: "origin/main", aheadCount: 3, behindCount: 0)
        #expect(s.inlineSuffix == "(+3 from remote)")
        #expect(s.tooltipText == "Upstream: main (3 ahead)")
    }

    @Test("Behind-only uses - count")
    func behindOnly() {
        let s = BranchUpstreamStatus(upstreamRef: "origin/main", aheadCount: 0, behindCount: 5)
        #expect(s.inlineSuffix == "(-5 from remote)")
        #expect(s.tooltipText == "Upstream: main (5 behind)")
    }

    @Test("Both ahead and behind")
    func both() {
        let s = BranchUpstreamStatus(upstreamRef: "origin/main", aheadCount: 2, behindCount: 4)
        #expect(s.inlineSuffix == "(+2 -4 from remote)")
        #expect(s.tooltipText == "Upstream: main (2 ahead, 4 behind)")
    }

    @Test("Negative/nil counts treated as zero")
    func clampsNegatives() {
        let s = BranchUpstreamStatus(upstreamRef: "origin/main", aheadCount: -1, behindCount: nil)
        #expect(s.inlineSuffix == nil) // both clamp to 0
    }

    @Test("displayUpstreamRef strips origin/ prefix but preserves others")
    func displayUpstreamRef() {
        #expect(BranchUpstreamStatus(upstreamRef: "origin/main").displayUpstreamRef == "main")
        #expect(BranchUpstreamStatus(upstreamRef: "upstream/dev").displayUpstreamRef == "upstream/dev")
    }
}

// MARK: - AppSettings helpers

@Suite("AppSettings static helpers")
struct AppSettingsStaticHelperTests {

    @Test("parseJiraTicketDetectionPrefixes splits on comma/semicolon/newline")
    func splitsDelimiters() {
        let result = AppSettings.parseJiraTicketDetectionPrefixes("ABC, def;GHI\njkl")
        #expect(result == ["ABC", "DEF", "GHI", "JKL"])
    }

    @Test("Trims whitespace and leading/trailing dashes")
    func trimsDashes() {
        let result = AppSettings.parseJiraTicketDetectionPrefixes("  -ABC-  , DEF--")
        #expect(result == ["ABC", "DEF"])
    }

    @Test("Drops empty entries")
    func dropsEmpty() {
        let result = AppSettings.parseJiraTicketDetectionPrefixes(",,  ,ABC,,,")
        #expect(result == ["ABC"])
    }

    @Test("Preserves input order")
    func preservesOrder() {
        let result = AppSettings.parseJiraTicketDetectionPrefixes("zzz, aaa, mmm")
        #expect(result == ["ZZZ", "AAA", "MMM"])
    }
}

// MARK: - AppSettings.command(for:)

@Suite("AppSettings.command(for:)")
struct AppSettingsCommandTests {

    private func settings(skipPermissions: Bool = false, sandboxEnabled: Bool = false, custom: String = "") -> AppSettings {
        AppSettings(
            activeAgents: [.claude, .codex, .custom],
            customAgentCommand: custom,
            agentSandboxEnabled: sandboxEnabled,
            agentSkipPermissions: skipPermissions
        )
    }

    @Test("Claude uses `command claude`, with skip-permissions flag when set")
    func claudeCommand() {
        #expect(settings(skipPermissions: false).command(for: .claude) == "command claude")
        #expect(settings(skipPermissions: true).command(for: .claude) == "command claude --dangerously-skip-permissions")
    }

    @Test("Codex picks --yolo / --full-auto / bare by mode")
    func codexCommand() {
        #expect(settings(skipPermissions: true, sandboxEnabled: false).command(for: .codex) == "command codex --yolo")
        #expect(settings(skipPermissions: false, sandboxEnabled: true).command(for: .codex) == "command codex --full-auto")
        #expect(settings(skipPermissions: false, sandboxEnabled: false).command(for: .codex) == "command codex")
        // Skip-permissions dominates sandbox
        #expect(settings(skipPermissions: true, sandboxEnabled: true).command(for: .codex) == "command codex --yolo")
    }

    @Test("Custom uses configured command, fallback when blank")
    func customCommand() {
        #expect(settings(custom: "").command(for: .custom) == "custom-agent")
        #expect(settings(custom: "   ").command(for: .custom) == "custom-agent")
        #expect(settings(custom: " my-tool --flag ").command(for: .custom) == "my-tool --flag")
    }
}

// MARK: - AppSettings.effectiveGlobalDefaultAgentType

@Suite("AppSettings.effectiveGlobalDefaultAgentType")
struct AppSettingsDefaultAgentTests {

    @Test("Nil when no active agents")
    func emptyActive() {
        let s = AppSettings(activeAgents: [])
        #expect(s.effectiveGlobalDefaultAgentType == nil)
    }

    @Test("Single active agent wins regardless of defaultAgentType")
    func single() {
        let s = AppSettings(activeAgents: [.codex], defaultAgentType: .claude)
        #expect(s.effectiveGlobalDefaultAgentType == .codex)
    }

    @Test("Uses defaultAgentType when it is among active agents")
    func usesDefault() {
        let s = AppSettings(activeAgents: [.claude, .codex], defaultAgentType: .codex)
        #expect(s.effectiveGlobalDefaultAgentType == .codex)
    }

    @Test("Falls back to first active when default is not available")
    func fallback() {
        let s = AppSettings(activeAgents: [.claude, .codex], defaultAgentType: .custom)
        #expect(s.effectiveGlobalDefaultAgentType == .claude)
    }

    @Test("availableActiveAgents de-duplicates while preserving order")
    func dedupe() {
        let s = AppSettings(activeAgents: [.claude, .codex, .claude, .custom, .codex])
        let available = s.availableActiveAgents
        #expect(s.effectiveGlobalDefaultAgentType == .claude)
        #expect(available == [.claude, .codex, .custom])
    }
}

// MARK: - ThreadSection decoding & color

@Suite("ThreadSection")
struct ThreadSectionTests {

    @Test("Decodes with isVisible/isKeepAlive defaults when fields missing")
    func legacyDecode() throws {
        let json = """
        {"id":"11111111-1111-1111-1111-111111111111","name":"Todo","colorHex":"#007AFF","sortOrder":0,"isDefault":true}
        """.data(using: .utf8)!
        let section = try JSONDecoder().decode(ThreadSection.self, from: json)
        #expect(section.isVisible == true)
        #expect(section.isKeepAlive == false)
        #expect(section.name == "Todo")
    }

    @Test("Honors explicit isVisible/isKeepAlive when present")
    func newFieldsDecode() throws {
        let json = """
        {"id":"11111111-1111-1111-1111-111111111111","name":"Hidden","colorHex":"#007AFF","sortOrder":1,"isDefault":false,"isVisible":false,"isKeepAlive":true}
        """.data(using: .utf8)!
        let section = try JSONDecoder().decode(ThreadSection.self, from: json)
        #expect(section.isVisible == false)
        #expect(section.isKeepAlive == true)
    }

    @Test("defaults() returns the four canonical sections")
    func defaults() {
        let defaults = ThreadSection.defaults()
        let names = defaults.map(\.name)
        let orders = defaults.map(\.sortOrder)
        let allDefault = defaults.allSatisfy(\.isDefault)
        #expect(defaults.count == 4)
        #expect(names == ["TODO", "In Progress", "Reviewing", "Done"])
        #expect(allDefault)
        #expect(orders == [0, 1, 2, 3])
    }

    @MainActor
    @Test("NSColor(hex:) parses 6-digit values with and without leading #")
    func colorHexValid() {
        #expect(NSColor(hex: "#FF0000") != nil)
        #expect(NSColor(hex: "00ff00") != nil)
        #expect(NSColor(hex: "  #0000ff  ") != nil)

        let red = NSColor(hex: "#FF0000")!.usingColorSpace(.sRGB)!
        var r: CGFloat = 0, g: CGFloat = 0, b: CGFloat = 0, a: CGFloat = 0
        red.getRed(&r, green: &g, blue: &b, alpha: &a)
        #expect(r == 1.0 && g == 0.0 && b == 0.0)
    }

    @MainActor
    @Test("NSColor(hex:) rejects wrong length or non-hex input")
    func colorHexInvalid() {
        #expect(NSColor(hex: "#FFF") == nil) // 3-digit short form not supported
        #expect(NSColor(hex: "#GGGGGG") == nil)
        #expect(NSColor(hex: "") == nil)
        #expect(NSColor(hex: "#1234567") == nil)
    }
}

// MARK: - IPCRequest

@Suite("IPCRequest decoding")
struct IPCRequestDecodingTests {

    @Test("Decodes create-web-tab payload with url and title")
    func decodesCreateWebTab() throws {
        let json = """
        {"command":"create-web-tab","threadName":"kimchi","url":"https://example.com/docs","title":"Docs"}
        """.data(using: .utf8)!
        let request = try JSONDecoder().decode(IPCRequest.self, from: json)
        #expect(request.command == "create-web-tab")
        #expect(request.threadName == "kimchi")
        #expect(request.url == "https://example.com/docs")
        #expect(request.title == "Docs")
    }

    @Test("url field is optional and absent on unrelated commands")
    func urlOptional() throws {
        let json = """
        {"command":"list-threads"}
        """.data(using: .utf8)!
        let request = try JSONDecoder().decode(IPCRequest.self, from: json)
        #expect(request.url == nil)
    }

    @Test("Decodes newName field for tab naming commands")
    func decodesNewName() throws {
        let json = """
        {"command":"create-tab","threadName":"kimchi","newName":"Review"}
        """.data(using: .utf8)!
        let request = try JSONDecoder().decode(IPCRequest.self, from: json)
        #expect(request.command == "create-tab")
        #expect(request.newName == "Review")
    }
}

// MARK: - PersistedWebTab

@Suite("PersistedWebTab display title")
struct PersistedWebTabDisplayTitleTests {

    @Test("Uses customTitle when present")
    func usesCustomTitle() throws {
        let url = try #require(URL(string: "https://example.com/docs"))
        let tab = PersistedWebTab(
            identifier: "web:test",
            url: url,
            title: "example.com",
            iconType: .web,
            customTitle: "Docs"
        )
        #expect(tab.displayTitle == "Docs")
    }

    @Test("Falls back to title when customTitle is nil")
    func fallsBackToTitle() throws {
        let url = try #require(URL(string: "https://example.com/docs"))
        let tab = PersistedWebTab(
            identifier: "web:test",
            url: url,
            title: "example.com",
            iconType: .web,
            customTitle: nil
        )
        #expect(tab.displayTitle == "example.com")
    }
}

// MARK: - IPCTabInfo

@Suite("IPCTabInfo")
struct IPCTabInfoTests {

    @Test("Carries optional tabType and keeps default nil")
    func tabTypeInitBehavior() {
        let terminal = IPCTabInfo(index: 0, sessionName: "ma-repo-thread", isAgent: true, tabType: "terminal")
        #expect(terminal.tabType == "terminal")

        let legacy = IPCTabInfo(index: 1, sessionName: "ma-repo-thread-2", isAgent: false)
        #expect(legacy.tabType == nil)
    }
}

// MARK: - ExternalLinkOpenRouting

@Suite("ExternalLinkOpenRouting")
struct ExternalLinkOpenRoutingTests {

    @Test("Prefers popped-out thread windows over main-window routes")
    func prefersPoppedOutThread() {
        let route = ExternalLinkOpenRouting.resolve(
            isThreadPoppedOut: true,
            isCurrentMainThread: true
        )
        #expect(route == .poppedOutThreadWindow)
    }

    @Test("Uses current main thread when the target thread is already visible")
    func currentMainThreadRoute() {
        let route = ExternalLinkOpenRouting.resolve(
            isThreadPoppedOut: false,
            isCurrentMainThread: true
        )
        #expect(route == .currentMainThread)
    }

    @Test("Selects the thread in the main window when not currently visible")
    func selectMainThreadRoute() {
        let route = ExternalLinkOpenRouting.resolve(
            isThreadPoppedOut: false,
            isCurrentMainThread: false
        )
        #expect(route == .selectThreadInMainWindow)
    }
}

// MARK: - ThreadTabStructureFingerprint

@Suite("ThreadTabStructureFingerprint")
struct ThreadTabStructureFingerprintTests {

    @Test("Ignores transient thread status fields")
    func ignoresTransientStatus() throws {
        let base = makeThread(
            tmuxSessions: ["ma-repo-thread-claude"],
            pinnedSessions: ["ma-repo-thread-claude"]
        )
        var updated = base
        updated.isDirty = true
        updated.isFullyDelivered = true
        updated.busySessions.insert("ma-repo-thread-claude")
        updated.waitingForInputSessions.insert("ma-repo-thread-claude")
        updated.unreadCompletionSessions.insert("ma-repo-thread-claude")

        #expect(ThreadTabStructureFingerprint(thread: base) == ThreadTabStructureFingerprint(thread: updated))
    }

    @Test("Changes when terminal sessions change")
    func changesOnTerminalSessions() throws {
        let base = makeThread(tmuxSessions: ["ma-repo-thread-claude"])
        let updated = makeThread(tmuxSessions: ["ma-repo-thread-claude", "ma-repo-thread-codex"])

        #expect(ThreadTabStructureFingerprint(thread: base) != ThreadTabStructureFingerprint(thread: updated))
    }

    @Test("Changes when web tabs or their pinning change")
    func changesOnWebTabs() throws {
        let webURL = try #require(URL(string: "https://example.com/docs"))
        let base = makeThread(
            webTabs: [
                PersistedWebTab(
                    identifier: "web:docs",
                    url: webURL,
                    title: "Docs",
                    iconType: .web,
                    isPinned: false
                ),
            ]
        )
        let updated = makeThread(
            webTabs: [
                PersistedWebTab(
                    identifier: "web:docs",
                    url: webURL,
                    title: "Docs",
                    iconType: .web,
                    isPinned: true
                ),
            ]
        )

        #expect(ThreadTabStructureFingerprint(thread: base) != ThreadTabStructureFingerprint(thread: updated))
    }

    @Test("Changes when draft tab identifiers change")
    func changesOnDraftTabs() {
        let base = makeThread(
            draftTabs: [
                PersistedDraftTab(identifier: "draft:1", agentType: .codex, prompt: "A"),
            ]
        )
        let updated = makeThread(
            draftTabs: [
                PersistedDraftTab(identifier: "draft:2", agentType: .codex, prompt: "A"),
            ]
        )

        #expect(ThreadTabStructureFingerprint(thread: base) != ThreadTabStructureFingerprint(thread: updated))
    }

    private func makeThread(
        tmuxSessions: [String] = [],
        pinnedSessions: [String] = [],
        webTabs: [PersistedWebTab] = [],
        draftTabs: [PersistedDraftTab] = []
    ) -> MagentThread {
        MagentThread(
            projectId: UUID(),
            name: "thread",
            worktreePath: "/tmp/thread",
            branchName: "thread",
            tmuxSessionNames: tmuxSessions,
            pinnedTmuxSessions: pinnedSessions,
            persistedWebTabs: webTabs,
            persistedDraftTabs: draftTabs
        )
    }
}

// MARK: - CreatedTerminalTabReconciler

@Suite("CreatedTerminalTabReconciler")
struct CreatedTerminalTabReconcilerTests {

    @Test("Prefers an existing created session over pending placeholder")
    func prefersExistingSession() {
        let placement = CreatedTerminalTabReconciler.resolvePlacement(
            createdSessionName: "ma-repo-thread-codex",
            displaySlots: ["ma-repo-thread-claude", "", "ma-repo-thread-codex"],
            pendingIndex: 1
        )

        #expect(placement == .alreadyPresent(index: 2))
    }

    @Test("Replaces pending placeholder when created session is not yet in display slots")
    func replacesPendingPlaceholder() {
        let placement = CreatedTerminalTabReconciler.resolvePlacement(
            createdSessionName: "ma-repo-thread-codex",
            displaySlots: ["ma-repo-thread-claude", ""],
            pendingIndex: 1
        )

        #expect(placement == .replacePending(index: 1))
    }

    @Test("Appends when pending index is no longer valid")
    func appendsWhenPendingIndexInvalid() {
        let placement = CreatedTerminalTabReconciler.resolvePlacement(
            createdSessionName: "ma-repo-thread-codex",
            displaySlots: ["ma-repo-thread-claude", "ma-repo-thread-web"],
            pendingIndex: 5
        )

        #expect(placement == .append)
    }

    @Test("Appends when pending slot is a non-terminal tab")
    func appendsWhenPendingSlotIsNonTerminal() {
        let placement = CreatedTerminalTabReconciler.resolvePlacement(
            createdSessionName: "ma-repo-thread-codex",
            displaySlots: ["ma-repo-thread-claude", nil],
            pendingIndex: 1
        )

        #expect(placement == .append)
    }
}
