import Foundation

enum ManagedShellStartup {
    static let agentProfile = "agent"
    static let profileVariable = "MAGENT_SHELL_PROFILE"
    static let managedFiles = [".zshenv", ".zprofile", ".zshrc", ".zlogin", ".zlogout"]

    static func contents(for fileName: String) -> String {
        switch fileName {
        case ".zshrc":
            return """
            # magent-zdotdir-v2
            if [ "${MAGENT_SHELL_PROFILE:-terminal}" != "agent" ]; then
              export ZDOTDIR="$HOME"
              if [ -f "$HOME/.zshrc" ]; then
                source "$HOME/.zshrc"
              fi
            fi
            if [ -n "${MAGENT_START_CWD:-}" ] && [ -d "${MAGENT_START_CWD}" ]; then
              cd -- "${MAGENT_START_CWD}" || true
            fi
            unset MAGENT_START_CWD
            start-agent() {
              local magent_session
              local magent_command
              magent_session="$(tmux display-message -p '#{session_name}' 2>/dev/null)" || {
                echo "start-agent: not running inside a Magent tmux session" >&2
                return 1
              }
              if [ -z "$magent_session" ]; then
                echo "start-agent: not running inside a Magent tmux session" >&2
                return 1
              fi
              magent_command="$(/tmp/magent-cli start-agent --session "$magent_session" --print-command)" || return $?
              if [ -z "$magent_command" ]; then
                echo "start-agent: Magent did not return an agent command" >&2
                return 1
              fi
              # The command string is generated by Magent for this tmux session.
              eval "$magent_command"
            }
            if [[ -o interactive && -z "${ZSH_EXECUTION_STRING:-}" && -z "${MAGENT_START_AGENT_NO_HINT:-}" && -z "${MAGENT_START_AGENT_HINT_SHOWN:-}" && -n "${MAGENT_SOCKET:-}" && -n "${MAGENT_AGENT_TYPE:-}" ]]; then
              export MAGENT_START_AGENT_HINT_SHOWN=1
              print -P "%F{8}Magent: run %Bstart-agent%b to launch or resume this tab's agent.%f"
            fi
            """
        case ".zshenv":
            return """
            # magent-zdotdir-v2
            if [ "${MAGENT_SHELL_PROFILE:-terminal}" != "agent" ] && [ -f "$HOME/.zshenv" ]; then
              source "$HOME/.zshenv"
            fi
            """
        case ".zprofile":
            return """
            # magent-zdotdir-v2
            if [ "${MAGENT_SHELL_PROFILE:-terminal}" = "agent" ]; then
              if [ -z "${MAGENT_AGENT_PATH_INITIALIZED:-}" ]; then
                typeset -U path PATH
                path=(
                  "$HOME/.local/bin"
                  "$HOME/.local/share/mise/shims"
                  "$HOME/.volta/bin"
                  "$HOME/.asdf/shims"
                  "$HOME/.bun/bin"
                  "$HOME/.cargo/bin"
                  "$HOME/Library/pnpm"
                  "$HOME"/.nvm/versions/node/*/bin(NOn)
                  /opt/homebrew/bin
                  /usr/local/bin
                  /usr/bin
                  /bin
                  /usr/sbin
                  /sbin
                  $path
                )
                export PATH MAGENT_AGENT_PATH_INITIALIZED=1
              fi
            elif [ -f "$HOME/.zprofile" ]; then
              source "$HOME/.zprofile"
            fi
            """
        case ".zlogin", ".zlogout":
            return """
            # magent-zdotdir-v2
            if [ "${MAGENT_SHELL_PROFILE:-terminal}" != "agent" ] && [ -f "$HOME/\(fileName)" ]; then
              source "$HOME/\(fileName)"
            fi
            """
        default:
            return "# magent-zdotdir-v2\n"
        }
    }
}
